### ISSUE TITLE
GPU memory cost issue related to "CLASSICAL" and "AGGREGATION"

### ISSUE THREAD

**Issue by Trigolds** [NVIDIA/AMGX#105]
I am trying to solve a relative large matrix.
I can get a good solution with the config file "GMRES_AMG_D2".
But, the classical algorithm somehow consumes lots of gpu memory.
Instead, the aggregation method consumes relative less gpu memory but with poor convergency.
Is is possible to reduce or control the gpu memory usage in case of classical algorithm?
Thanks in advance.

**Comment by marsaev** [comment]
Unfortunately by the nature of classical algorithm it just requires significantly more memory - we currently explicitly store process galrkin product matrices. There are possible improvements to the implementation but it's impossible to reduce memory consumption significantly right now. You can probably save a little bit of memory by reducing restart number for gmres (gmres_n_restart parameter) for the cost of some convergence.

**Comment by Trigolds** [comment]
Thanks a lot. I will try to reduce the restart number.
