### ISSUE TITLE
 No CUDA-capable device is detected.

### ISSUE THREAD

**Issue by luohuizhang** [NVIDIA/AMGX#106]
Hi, I ran the multi GPU example from the build directory on Summit,  and I got the errors as:
bash-4.2$ jsrun -n 2 examples/amgx_mpi_capi -m ../examples/matrix.mtx -c ../core/configs/FGMRES_AGGREGATION.json
Cuda error in file 'luo/AMGX/examples/amgx_mpi_capi.c' in line 149 : no CUDA-capable device is detected.
Cuda error in file 'luo/AMGX/examples/amgx_mpi_capi.c' in line 149 : no CUDA-capable device is detected.

The cuda version is 10.1.243.
I got the following information with nvidia-smi:
bash-4.2$  nvidia-smi
Fri Aug  7 15:27:25 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.116.00   Driver Version: 418.116.00   CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000004:04:00.0 Off |                    0 |
| N/A   37C    P0    36W / 300W |      0MiB / 16130MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000004:05:00.0 Off |                    0 |
| N/A   41C    P0    36W / 300W |      0MiB / 16130MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  On   | 00000035:03:00.0 Off |                    0 |
| N/A   36C    P0    36W / 300W |      0MiB / 16130MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  On   | 00000035:04:00.0 Off |                    0 |
| N/A   44C    P0    37W / 300W |      0MiB / 16130MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+

Do you have any idea of what happened, I had tried a week to figure out the problem but I failed.

Thanks for your time and waiting for you reponse.

Ross

**Comment by marsaev** [comment]
Please, refer to the summit guide to see how you allocate GPUs: https://docs.olcf.ornl.gov/systems/summit_user_guide.html#resource-sets

Thanks,

**Comment by luohuizhang** [comment]
Thanks so much, the problem is solved.
Have a good weekend!
