### ISSUE TITLE
CUDA 11 support

### ISSUE THREAD

**Issue by piyueh** [NVIDIA/AMGX#107]
Hi, does the latest commit of AmgX support CUDA 11?

When building the AmgX library, I got some undefined symbols: `cusparseScsrmv`, `cusparseDcsrmv`, `cusparseCcsrmv`, `cusparseZcsrmv`, `cusparseScsrmm`, `cusparseDcsrmm`, `cusparseCcsrmm`, and `cusparseZcsrmm`. According to cuSPARSE v10.1 manual, these functions would be removed from the next major release, which is v11.

I also got these warnings:
1. `Thrust requires C++14. Please pass -std=c++14 to your compiler. Define THRUST_IGNORE_DEPRECATED_CPP_DIALECT to suppress this message.`
2. `CUB requires C++14. Please pass -std=c++14 to your compiler. Define CUB_IGNORE_DEPRECATED_CPP_DIALECT to suppress this message.`

Thanks!

**Comment by marsaev** [comment]
Yep, we will release small update that addresses those errors/warnings soon. C++14 requirement from compiler would also be mandatory - it's relatively soft jump from C++11, but will leave us prepared for future thrust release.

**Comment by DeanLym** [comment]
Hi, I am having the same issue with CUDA11. Specifically I am building in WSL2. It is not clear if CUDA10 is supported in WSL2. Looking forward to the update.

**Comment by rosaline1995** [comment]
May I ask whether changing CUDA from 11 to lower versions can solve this issue/error/warning or not?
Thanks!

**Comment by piyueh** [comment]
@rosaline1995 For me, yes. Both CUDA 10.1 and 10.2 work for me.

**Comment by rosaline1995** [comment]
@piyueh Thanks! That's nice!

**Comment by tbrandvik** [comment]
Just checking if there are any updates on CUDA 11 support? Thanks!

**Comment by marsaev** [comment]
@tbrandvik you can try checking out v2.1.x branch where we merged CUDA 11 changes

**Comment by tbrandvik** [comment]
@marsaev Perfect, thanks!

**Comment by marsaev** [comment]
Merged to `main`, also available in release 2.2.0
