### ISSUE TITLE
AMGX_matrix_upload_all_global fails with 'out of memory' error

### ISSUE THREAD

**Issue by joconnor22** [NVIDIA/AMGX#110]
I'm having some difficulty filling up the entire memory on the GPU. When I call `AMGX_matrix_upload_all_global` I get: 

```Thrust failure: parallel_for failed: out of memory```

However, when I total up the memory allocated for `row_ptrs`, `col_indices_global`, and `data` it only comes to about 40% of the available memory on the GPU. Note that I have tested a few different GPUs and it always comes to about 40% when I start getting the error.

Having had a brief look at the source code it seems the `DistributedManager` allocates a new block of memory and copies the `data` values into this new block (effectively having two copies of the same data). Is this right? Is there a way around this since this effectively halves the achievable problem size?

I realise that, being a distributed solver, AMGX probably wasn't built with memory consumption as a priority. However, for legacy reasons I am limited to multi-GPU/single-node systems at the moment so was wondering if there is a way around this?

Happy to provide a MWE if required.

**Comment by Jaberh** [comment]
Just a friendly note, 
you can use 
cudaMemGetInfo(&free_mem, &total); 
before that call to see the real available memory rather than theoretical memory.

**Comment by joconnor22** [comment]
Thanks for your reply. Yes I am aware of that. The issue still stands though. In fact, this occurs even when I pass the arrays as CPU pointers to `AMGX_matrix_upload_all_global`. In other words, it occurs even when there is no memory allocated on the GPU prior to calling `AMGX_matrix_upload_all_global`.

**Comment by Jaberh** [comment]
Irrelevant question. Are you using pinned memory?

**Comment by joconnor22** [comment]
No I am not. Can you explain why you think that might be important?

**Comment by Jaberh** [comment]
OS can limit the amount of pinned memory.

**Comment by joconnor22** [comment]
OK yes it probably isn't that then.

**Comment by marsaev** [comment]
Are you forced to use specific solver configurations? Aggregation multigrid is better with memory usage even in distributed settings.

But yes, peak memory usage might be pretty large for classical, would need investigation on the code to understand how this can be improved.

**Comment by joconnor22** [comment]
Thanks for the reply. So using the Aggregation multigrid doesn't help in this instance. I'm guessing because it is the call to `AMGX_matrix_upload_all_global` that is throwing the out-of-memory error (even though the `row_ptrs`, `col_indices_global`, and `data` arrays only use about 40% of the available memory). I'm assuming this call is more or less independent of the solver configuration and the bulk of the solver-specific initialisation occurs in `AMGX_solver_setup`. Instead, it looks like `AMGX_matrix_upload_all_global` makes duplicate copies of the input arrays which is why I'm getting the error. Is this right?

**Comment by marsaev** [comment]
> I'm assuming this call is more or less independent of the solver configuration and the bulk of the solver-specific initialisation occurs in AMGX_solver_setup
Main solver parameter that controls how much memory would be allocated in `AMGX_matrix_upload_all_global` is whether multigrid is classical or aggregation with latter using less memory.
> Instead, it looks like AMGX_matrix_upload_all_global makes duplicate copies of the input arrays which is why I'm getting the error. Is this right?
Yes, we do indeed copy input data to internal buffers. For multigpu multigrid this copy is modified (reordered) - that's why we are working with a copy.

**Comment by joconnor22** [comment]
OK thanks for the info. I'm guessing there's no way around that so I'm happy to close the ticket.
