### ISSUE TITLE
Comparison of AMGX and Hypre

### ISSUE THREAD

**Issue by TXTsky** [NVIDIA/AMGX#112]
Dear Developer，
After reading your  _"AmgX: A Library for GPU Accelerated Algebraic Multigrid and Preconditioned Iterative Methods"_， I am very interested in the comparison between your experiment(AMGX) and Hypre. This is a very meaningful work, but I don't know the parameters used in your experiment.
I want to reproduce your comparative experiment, and I would be very grateful if you can help me. Can you tell me the commands you used when running AMGX and Hypre?
My GPU platform is 8×2060s server, CUDA10.2, AMGX V2.1.0 and Hypre 2.19.0.

Respect and best wishes!

**Comment by marsaev** [comment]
Ok, it might take a little bit of time to dig the exact configuration, but this should be something like following AMGX config:
```
{
    "config_version": 2, 
    "print_grid_stats": 1, 
    "store_res_history": 1, 
    "solver" : "FGMRES", 
    "print_solve_stats": 1, 
    "obtain_timings": 1, 
    "preconditioner": {
        "interpolator": "D2", 
        "print_grid_stats": 1, 
        "aggressive_levels": 1, 
        "solver": "AMG", 
        "smoother": {
            "relaxation_factor": 1.0, 
            "scope": "jacobi", 
            "solver": "JACOBI_L1"
        }, 
        "presweeps": 2, 
        "selector": "PMIS", 
        "coarsest_sweeps": 2, 
        "coarse_solver": "NOSOLVER", 
        "max_iters": 1, 
        "max_row_sum": 0.9, 
        "strength_threshold": 0.25, 
        "min_coarse_rows": 1,
        "scope": "amg_solver", 
        "max_levels": 24, 
        "cycle": "V", 
        "postsweeps": 2,
        "interp_max_elements": 4
    }, 
    "max_iters": 100, 
    "monitor_residual": 1, 
    "gmres_n_restart": 10, 
    "convergence": "RELATIVE_INI_CORE", 
    "tolerance": 1e-07, 
    "norm": "L2"
}
```

For hypre we used GMRES solver (`HYPRE_ParCSRGMRESCreate()`) preconditionded with BoomerAMG (`HYPRE_BoomerAMGCreate()`). And matching parameters were used for HYPRE solver.
