### ISSUE TITLE
Unsteady solver using AMGX prints "Using Normal MPI (Hostbuffer) communicator..." data repeatedly

### ISSUE THREAD

**Issue by Jaberh** [NVIDIA/AMGX#115]
Hi marsaev

I think the sentence buffer is being printed too many times
and clutters the log file, I think we talked about this before
Is there any update on removing this to a higher level ? 
here is what I get when I run a simulation
[ 0.00%] ncyc        1;  Crank -146.995 (deg); dt=    6.250000000e-07 
Using Normal MPI (Hostbuffer) communicator...
[  0.00%] ncyc        2;  Crank -146.989 (deg); dt=    7.812500000e-07 
Using Normal MPI (Hostbuffer) communicator...
[  0.01%] ncyc        3;  Crank -146.982 (deg); dt=    9.765625000e-07 
Using Normal MPI (Hostbuffer) communicator...
[  0.01%] ncyc        4;  Crank -146.972 (deg); dt=    1.220703125e-06 
Using Normal MPI (Hostbuffer) communicator...
[  0.01%] ncyc        5;  Crank -146.961 (deg); dt=    1.525878906e-06 
Using Normal MPI (Hostbuffer) communicator...
[  0.02%] ncyc        6;  Crank -146.946 (deg); dt=    1.907348633e-06 
Using Normal MPI (Hostbuffer) communicator...

**Comment by marsaev** [comment]
Hey,
Yes, it seems this output is unconditional, will hide it under higher verbosity level, should be a short change.

**Comment by Jaberh** [comment]
Spasiba
