### ISSUE TITLE
Cannot compile with sm30 on Quadro K1100

### ISSUE THREAD

**Issue by robertsawko** [NVIDIA/AMGX#12]
Hi,

So I am looking at compiling AmgX on my laptop Quadro K1100. After making the changes discussed here #11 the project compiles but running examples won't work `no kernel image is available for execution on the device`. I checked the `CMakeLists.txt` and of coursed it's because we are fixing CUDA_ARCH to sm35 and greater. So I go back to my configuration and based on [this website](https://developer.nvidia.com/cuda-gpus) I put `sm30` in my config and compile procedure:

```bash
install_dir=${HOME}/apps/amgx
build_dir=build-gcc-ompi

# clean
rm -rf $build_dir
mkdir $build_dir
cd $build_dir

export OMPI_CC=/opt/cuda/bin/gcc
export OMPI_CXX=/opt/cuda/bin/g++

cmake \
    -DCMAKE_INSTALL_PREFIX=$install_dir \
    -DCMAKE_C_COMPILER=/opt/cuda/bin/gcc \
    -DCUDA_ARCH="30" \
    -DCMAKE_CXX_COMPILER=/opt/cuda/bin/g++ \
    ../ && make -j2 && make install
```

Alas, this breaks pretty early on producing lots of errors. See the [file attached](https://github.com/NVIDIA/AMGX/files/1677061/errors.txt). I am investigating it independently, but if you have and advice, please let me know.

**Comment by marsaev** [comment]
Hi @robert,

I think source of this error is:
https://github.com/NVIDIA/AMGX/blob/265a398bafce0d4950b283967796d263df185144/core/src/aggregation/coarseAgenerators/low_deg_coarse_A_generator.cu#L411

Switch should happen on 300 since there are two versions of warp reduce - pre- and post-3.0 CC. Can you change this line to '#if __CUDA_ARCH__ >= 300' and see if it will work?

**Comment by robertsawko** [comment]
That didn't help on its own, but I greped (is that verb?) for more places where `warp_reduce` was used and got 

https://github.com/NVIDIA/AMGX/blob/265a398bafce0d4950b283967796d263df185144/core/src/aggregation/coarseAgenerators/low_deg_coarse_A_generator.cu#L886-L888

and 

https://github.com/NVIDIA/AMGX/blob/265a398bafce0d4950b283967796d263df185144/core/src/aggregation/coarseAgenerators/low_deg_coarse_A_generator.cu#L1082-L1083

I changed those too and got it going further.

**Comment by robertsawko** [comment]
That seems to have clinched it. I got it to compile and run the basic example and I am sending #14 . Please review.

**Comment by marsaev** [comment]
Thanks for the PR! Closing the issue.
