### ISSUE TITLE
AMGX_solver_get_iterations_number  reports 1 iteration higher than terminal output

### ISSUE THREAD

**Issue by artv3** [NVIDIA/AMGX#126]
Hi all, 

In my application I noticed that the ``AMGX_solver_get_iterations_number()`` method reports 1 iteration more than what is reported on the terminal. For example, I might see: 

```
         --------------------------------------------------------------
         Total Iterations: 132
         Avg Convergence Rate: 		         0.9076
         Final Residual: 		   9.097104e-08
         Total Reduction in Residual: 	   2.759275e-06
         Maximum Memory Usage: 		          0.881 GB
         --------------------------------------------------------------
```

but using the ``AMGX_solver_get_iterations_number()`` I would get one iteration higher: Number of iterations 133 
. Is this a bug? or is my usage incorrect? Thanks.

**Comment by sbna** [comment]
Thanks @artv3 for the issue, I confirm the same behaviour in all my tests.

**Comment by mattmartineau** [comment]
Hi - it looks to be intentional, but certainly incorrect in my opinion. The offending code is:

```
template<AMGX_Mode CASE>
inline void solver_get_iterations_number(AMGX_solver_handle slv, int *n)
{
    ...
    *n = solver->get_num_iters() + 1;
}
```

The call `solver->get_num_iters()` just returns `m_num_iters`, which is what you see printed in the terminal output.

So I'm not sure why the deliberate increment exists but it's easily fixed.

**Comment by KristofferC** [comment]
This has also been noticed in the Python wrappers:

https://github.com/shwina/pyamgx/blob/ef96ecf78223460689b443ac63dc9c4c0a79dd7e/pyamgx/Solver.pyx#L118-L119

and the Julia wrappers:

https://github.com/JuliaGPU/AMGX.jl/blob/369518dad3062da72ef3b7046b23d0c2f92e442d/src/Solver.jl#L62-L63

**Comment by artv3** [comment]
I've proposed a PR here https://github.com/NVIDIA/AMGX/pull/131.
