### ISSUE TITLE
AMGx on distributed GPU Cluster

### ISSUE THREAD

**Issue by manasi-t24** [NVIDIA/AMGX#129]
Hello,
I am interested in using the Krylov subspace sparse iterative solvers in AMGx (specifically, CG).

1. Does AMGx support CG with multiple GPUs? Within the same node and across multiple nodes?
2. If we can use CG on multiple GPUs, how are MPI ranks mapped to the GPU? Can only one MPI rank offload its data structures and computations to its GPU (one to one mapping) or can many MPI ranks use the same GPU (many to one mapping). 
3. Are there any optimizations done in AMGx while implementing CG method?

Regards,
Manasi

**Comment by marsaev** [comment]
> Does AMGx support CG with multiple GPUs? Within the same node and across multiple nodes?

Yes. We use MPI for multi-device processing and for AMGX it doesn't matter where processes are allocated - as long as mpi will communicate between them.

> If we can use CG on multiple GPUs, how are MPI ranks mapped to the GPU? Can only one MPI rank offload its data structures and computations to its GPU (one to one mapping) or can many MPI ranks use the same GPU (many to one mapping).

It is _allowed_ for multiple MPI ranks share same GPU but it definitely would be not the optimal way. Couple of possible solutions:
1) Use number of MPI ranks equal to the number of GPUs. This will simplify AMGX usage but will probably slow down rest of your CPU workload
2) Use consolidation inside AMGX - this is function inside amgx that allows multiple MPI ranks to combine their data on a single GPU and having only single process "control" solving process - the rest will wait for the solve to complete. You can read about consolidation in the documentation.

> Are there any optimizations done in AMGx while implementing CG method?

No, most of the benefit comes from matrix-vector product done on GPU

**Comment by manasi-t24** [comment]
Thanks for the clarifications.
Can you point me to the AMGx documentation?

Regards,
Manasi

**Comment by mattmartineau** [comment]
Here: https://github.com/NVIDIA/AMGX/tree/main/doc
