### ISSUE TITLE
Mode switch missing in the docs?

### ISSUE THREAD

**Issue by robertsawko** [NVIDIA/AMGX#13]
Indepdently, I got AmgX to compile on K80s on our cluster and I can now can run the examples. It seems to me that `-mode` switch is missing in `README.md` e.g. this
```
examples/amgx_capi -m ../examples/matrix.mtx -c ../core/configs/FGMRES_AGGREGATION.json
```

Should be probably something like:
```
examples/amgx_capi -mode dDDI -m ../examples/matrix.mtx -c ../core/configs/FGMRES_AGGREGATION.json
```

Happy to provide an independent pull request with `README.md` update and a tabular description of modes if you think it's useful.

**Comment by marsaev** [comment]
Yes, mode 'device double(matrix) double(vector) int' is used by default. I will put short description of modes to readme.

**Comment by robertsawko** [comment]
My mistake, I am closing it as I can't reproduce. On some of my previous runs of `amgx_capi` I was getting `mode not specified` error, but clearly this must have been something different.
