### ISSUE TITLE
Build error- nvcc fatal   :Unsupported PGI compiler found

### ISSUE THREAD

**Issue by NandanS-git** [NVIDIA/AMGX#150]
I am getting an error while building the AMGX package from branch 'main',

```
nvcc fatal   : Unsupported PGI compiler found.  pgc++ is the only PGI compiler that is supported.
nvcc fatal   : Unsupported PGI compiler found.  pgc++ is the only PGI compiler that is supported.
CMake Error at amgx_base_generated_coarse_A_generator.cu.o.cmake:210 (message):
  Error generating
  /home/sroy/debajyoti/AMGX/build/base/CMakeFiles/amgx_base.dir/src/aggregation/coarseAgenerators/./amgx_base_generated_coarse_A_generator.cu.o

 


CMake Error at amgx_base_generated_plugin_config.cu.o.cmake:210 (message):
  Error generating
  /home/sroy/debajyoti/AMGX/build/base/CMakeFiles/amgx_base.dir/__/./amgx_base_generated_plugin_config.cu.o

 


make[2]: *** [base/CMakeFiles/amgx_base.dir/src/aggregation/coarseAgenerators/./amgx_base_generated_coarse_A_generator.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [base/CMakeFiles/amgx_base.dir/__/./amgx_base_generated_plugin_config.cu.o] Error 1
[  6%] [  6%] nvcc fatal   : Unsupported PGI compiler found.  pgc++ is the only PGI compiler that is supported.
CMake Error at amgx_base_generated_amg_signal.cu.o.cmake:210 (message):
```

I have loaded the following software packages:
1. NVIDIA HPC SDK 21.3
2. CUDA TOOLKIT 11.1.0
3. CMAKE 2.8.12.2
4. Compiler version:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Tue_Sep_15_19:10:02_PDT_2020
Cuda compilation tools, release 11.1, V11.1.74
Build cuda_11.1.TC455_06.29069683_0

The OS is Centos 7. Please help identify the bug. Thanks.

**Comment by nvarini** [comment]
I also stumbled upon this error. You can try to type ccmake .. Then change CUDA_HOST_COMPILER=pgc++. Then the compilation starts but I do get the error: 
"/ssoft/spack/arvine/v1/opt/spack/linux-rhel7-skylake_avx512/gcc-8.4.0/cuda-10.
          2.89-me54vzxwg5jte2t7hudufegfqriancnp/include/crt/host_config.h",
          line 118: catastrophic error: #error directive: -- unsupported pgc++
          configuration! Only pgc++ 18 and 19 are supported!
  #error -- unsupported pgc++ configuration! Only pgc++ 18 and 19 are supported!
   ^

1 catastrophic error detected in the compilation of "/home/nvarini/nvhpc_stack/AMGX/core/src/api_version.cu".
Compilation terminated.
CMake Error at amgx_core_generated_api_version.cu.o.cmake:210 (message):
  Error generating
  /home/nvarini/nvhpc_stack/AMGX/build/core/CMakeFiles/amgx_core.dir/src/./amgx_core_generated_api_version.cu.o

I wonder why AMGX compiles fine with CUDA_HOST_COMPILER=gcc but it requires c++ in case of nvhpc.

**Comment by NandanS-git** [comment]
Thanks for the reply, I finally used gcc version 7.4.0 along with cuda 11.2. It compiled without any errors. Prior, there were errors related to libstdc++.so shipped with centos 7 regarding insufficient CXXABI version and GLIBC. So manually directing to the libstdc++.so.6 provided by gcc 7.4 helped the case and AMGX was successfully built.

**Comment by marsaev** [comment]
Sorry for the late reply.
Latest NVHPC releases fixed some of the issues related to the compiler. We've also updated cmake to handle cuda in more robust manner. Since you've been able to build eventually closing this issue. Please open new one if you have different error with latest AMGX code revision, we'll try to keep build stable with nvhpc and we'll look at new issues.

Thanks,
