### ISSUE TITLE
Support for Systems of PDEs

### ISSUE THREAD

**Issue by wcdawn** [NVIDIA/AMGX#152]
I have been using AmgX (with [MFEM](https://github.com/mfem/mfem)) for some simple problems and would like to try some more complicated ones. These more complicated problems are a system of coupled PDEs that have been discretized with FEM which results in a vector of unknowns at each grid point. Common examples would be a velocity field or displacement in a mechanics calculation.

Other AMG packages like [HYPRE](https://github.com/hypre-space/hypre) or [PETSc](https://gitlab.com/petsc/petsc) provide an to specify the number of unknowns at each grid point (e.g., `NumFunctions` in HYPRE) which allows for a dramatic improvement in the performance of the coarsening levels.

It looks like AmgX has something called `blockdim` but it looks like only `blockdim=1` is supported in general. Are there any plans to allow for the use of AmgX for matrices representing systems of PDEs?
Thanks!

**Comment by marsaev** [comment]
Hi, @wcdawn ,

You are correct, there is no support for coupled equations for some parts of AMGX (i.e. CLASSICAL multigrid doesn't support coupled systems at all), however some configurations will work with `blockdim` up to 5. I.e. this configuration: https://github.com/NVIDIA/AMGX/blob/main/core/configs/FGMRES_AGGREGATION_JACOBI.json

**Comment by wcdawn** [comment]
@marsaev Thanks for the info!
The problems I am considering represent a coupled system of 1000+ PDEs which seems to be out of the scope of AmgX for now.
I'm glad to close this issue, but would be interested in more general support for systems of PDEs in the future.
