### ISSUE TITLE
number of PC iterations in provided PCG_DILU.json configuration file

### ISSUE THREAD

**Issue by F08H15** [NVIDIA/AMGX#153]
Good day. 
Is my understanding of the provided PCG_DILU.json  configuration file (in ~/core/config) correct, that, as no explicit value of "max_iters" is set for the DILU preconditioner, the latter will perform 100 iterations per PCG step? Any insight will be appreciated.

**Comment by marsaev** [comment]
You are correct, default `max_iters` value for any solver is 100: 
https://github.com/NVIDIA/AMGX/blob/main/core/src/core.cu#L535

Only exception is dense exact solver, which overrides this value to 1: 
https://github.com/NVIDIA/AMGX/blob/main/core/src/solvers/dense_lu_solver.cu#L687
