### ISSUE TITLE
What's the effect of the PC choice in the configuration file CG_DILU.json?

### ISSUE THREAD

**Issue by F08H15** [NVIDIA/AMGX#154]
Good day. The AMGX sources provide the configuration file CG_DILU.json in ~/core/configs. 
Now, is it possible that the CG solver simply ignores any preconditionner setting? 
The residual norms in two runs, one with CG_DILU.json and another one with PCG_NOPREC.json (modified to allow for the same maximum number of iterations), are identical to the last digit.
As always, any insight appreciated.

**Comment by marsaev** [comment]
This is correct, CG is non-preconditioned conjugate gradient method and ignores preconditioner parameter, while PCG (which stands just for Preconditioned Conjugate Gradient) will use preconditioner parameter, and will be equivalent to CG if no such parameter is set.
