### ISSUE TITLE
AmgX issue with Cuda 11.4 ?

### ISSUE THREAD

**Issue by pledac** [NVIDIA/AMGX#156]
Hi all,

Is it possible there is an issue with Cuda 11.4 ? I run AmgX fine with Cuda 11.2 but a quick try on a more recent version (11.4) got the error message:

_AMGX ERROR: Error initializing amgx core.
AMGX version 2.1.0.131-opensource
Built on Oct  4 2021, 15:14:17
Failed while initializing CUDA runtime in cudaRuntimeGetVersionCuda error in file '/home/ledacp/trust/ThirdPart/src/LIBAMGX/AmgX/examples/amgx_mpi_capi.c' in line 149 : **no CUDA-capable device is detected.**

**I checked that my Cuda install (Ubuntu 20.04 box with gcc 9.3.0) is ok:**
/home/ledacp/trust/ThirdPart/src/LIBAMGX:../../../env/nvc_get_devices/nvc_get_devices
Found 1 platform(s).
Using platform: NVIDIA Corporation NVIDIA CUDA Driver
CUDA Driver Version:                           11.40

Device 0: "NVIDIA GeForce RTX 2060"
  Type of device:                                GPU
  Compute capability:                            7.5
  Double precision support:                      Yes
  Total amount of global memory:                 6 GB
  Number of compute units/multiprocessors:       30
  Number of cores:                               5760
  Total amount of constant memory:               65536 bytes
  Total amount of local/shared memory per block: 49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per block:           1024
  Maximum group size (# of threads per block)    1024 x 1024 x 64
  Maximum item sizes (# threads for each dim)    2147483647 x 65535 x 65535
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Clock rate:                                    1.68 GHz
  Run time limit on kernels:                     Yes
  Integrated:                                    No
  Support host page-locked memory mapping:       Yes
  Compute mode:                                  Default
  Concurrent kernel execution:                   Yes
  Device has ECC support enabled:                No

Thanks,

**Comment by cjmcclellan** [comment]
I was able to build AmgX with CUDA 11.4. Your CUDA installation may have had issues.

GPU: NVIDIA GeForce 3050 Ti
Driver: 470.42.01
CUDA Version: 11.4
GCC/G++ Version: 9.3.0 (I had an issue using 10.3)
No MPI and No MAGMA

**Comment by marsaev** [comment]
@pledac can you try with the latest version of the code? 

Thanks,

**Comment by pledac** [comment]
Hope I could try this week-end and report.

**Comment by pledac** [comment]
Works now with master (commit 9304db908c5e). Sorry, I was on a old commit (6dba8067, January 2021). Thanks all.
