### ISSUE TITLE
Win10 + VS2019 + CUDA11.4 compile passed,using comic examples test by amgx_capi.exe,the result almost is wrong

### ISSUE THREAD

**Issue by zhouhansheng** [NVIDIA/AMGX#160]
the following is test comand line :
**amgx_capi -m matrix.mtx -c** **FGMRES_AGGREGATION.json**
I found the matrix.mtx could read,but json file could not work.
**the iter is always 0,residual is always -1.00000e+00**.Obviously it is wrong.
When i use other json files , the condition is same.![Uploading Snipaste_2
![Snipaste_2021-11-22_15-38-00](https://user-images.githubusercontent.com/52910765/142821876-8c1aa404-e5e6-4bf9-84f3-5d6b47914311.png)
021-11-22_15-38-00.png…]()

**Comment by zhouhansheng** [comment]
![image](https://user-images.githubusercontent.com/52910765/142822146-2a65c986-eda6-4a63-a714-18b4abb58e7d.png)

**Comment by zhouhansheng** [comment]
![Snipaste_2021-11-22_15-49-39](https://user-images.githubusercontent.com/52910765/142823028-0650b207-523c-4cb5-ad95-c30d37256f9a.png)
when i use **amgx_mpi_capi.exe**,the condition is really like above

**Comment by mattmartineau** [comment]
This should be fixed by the most recent commit. Did you try that?

**Comment by mattmartineau** [comment]
This should be fixed by the most recent commit. Did you try that?

**Comment by zhouhansheng** [comment]
> This should be fixed by the most recent commit. Did you try that?
Now the results of **amgx_capi.exe** seem is right.

amgx_capi -m matrix.mtx -c FGMRES_AGGREGATION.json
------------------------------------------------------------------------------------------------------------------------------------
AMGX version 2.2.0.132-opensource
Built on Nov 30 2021, 18:41:42
Compiled with CUDA Runtime 11.0, using CUDA driver 11.4
Warning: No mode specified, using dDDI by default.
Reading data...
RHS vector was not found. Using RHS b=[1,鈥?1]^T
Solution vector was not found. Setting initial solution to x=[0,鈥?0]^T
Finished reading
AMG Grid:
         Number of Levels: 1
            LVL         ROWS               NNZ    SPRSTY       Mem (GB)
         --------------------------------------------------------------
           0(D)           12                61     0.424       8.75e-07
         --------------------------------------------------------------
         Grid Complexity: 1
         Operator Complexity: 1
         Total Memory Usage: 8.75443e-07 GB
         --------------------------------------------------------------
           iter      Mem Usage (GB)       residual           rate
         --------------------------------------------------------------
            Ini             1.83118   3.464102e+00
              0             1.83118   2.183701e-14         0.0000
         --------------------------------------------------------------
         Total Iterations: 1
         Avg Convergence Rate:                   0.0000
         Final Residual:                   2.183701e-14
         Total Reduction in Residual:      6.303801e-15
         Maximum Memory Usage:                    1.831 GB
         --------------------------------------------------------------
Total Time: 0.005116
    setup: 0.00258672 s
    solve: 0.00252928 s
    solve(per iteration): 0.00252928 s
------------------------------------------------------------------------------------------------------------------------------
Thank you for your reply!
