### ISSUE TITLE
GCC10.3, OpenMPI-4.1.1, CUDA-11.3: Build failing after commit of Jan 25, 2022

### ISSUE THREAD

**Issue by swenczowski** [NVIDIA/AMGX#166]
Dear AmgX developers,

we initially intended to build PETSc with AmgX support. For this purpose, we checked out the repository https://github.com/mattmartineau/petsc.git and configured as follows:

`./configure --CFLAGS=-O2 -ftree-vectorize -march=native -fno-math-errno -fPIC --CXXFLAGS=-O2 -ftree-vectorize -march=native -fno-math-errno -fPIC -DOMPI-SKIP-MPICXX -DMPICH-SKIP-MPICXX --FFLAGS=-O2 -ftree-vectorize -march=native -fno-math-errno -fPIC --download-chaco-shared=0 --download-chaco=1 --download-hypre-shared=0 --download-hypre=1 --download-mumps-shared=0 --download-mumps=1 --download-spai-shared=0 --download-spai=1 --download-superlu-shared=0 --download-superlu=1 --download-superlu_dist-shared=0 --download-superlu_dist=1 --download-triangle=1 --with-blaslapack-lib=[/p/software/juwelsbooster/stages/2020/software/imkl/2021.2.0-gompi-2021/mkl/2021.2.0/lib/intel64/libmkl_gf_lp64.a,libmkl_sequential.a,libmkl_core.a,libgfortran.a] --with-build-step-np=40 --with-c++-support --with-cuda-dir=/p/software/juwelsbooster/stages/2020/software/CUDA/11.3 --with-cuda=1 --with-cxx-dialect=C++11 --with-debugging=0 --with-fftw-include=/p/software/juwelsbooster/stages/2020/software/imkl/2021.2.0-gompi-2021/mkl/2021.2.0/include/fftw --with-fftw-lib=[/p/software/juwelsbooster/stages/2020/software/imkl/2021.2.0-gompi-2021/mkl/2021.2.0/lib/intel64/libfftw3xc_gnu_pic.a,libfftw3x_cdft_lp64_pic.a,libmkl_cdft_core.a,libmkl_blacs_openmpi_lp64.a,libmkl_gf_lp64.a,libmkl_sequential.a,libmkl_core.a,libgfortran.a] --with-fftw=1 --with-hdf5-dir=/p/software/juwelsbooster/stages/2020/software/HDF5/1.10.6-gompi-2021 --with-hdf5=1 --with-large-file-io --with-metis-dir=/p/software/juwelsbooster/stages/2020/software/METIS/5.1.0-GCC-10.3.0 --with-metis=1 --with-mpi=1 --with-openmp=1 --with-parmetis-dir=/p/software/juwelsbooster/stages/2020/software/ParMETIS/4.0.3-gompi-2021 --with-parmetis=1 --with-pic=1 --with-scalapack-include=/p/software/juwelsbooster/stages/2020/software/imkl/2021.2.0-gompi-2021/mkl/2021.2.0/include --with-scalapack-lib=[/p/software/juwelsbooster/stages/2020/software/imkl/2021.2.0-gompi-2021/mkl/2021.2.0/lib/intel64/libmkl_scalapack_lp64.a,libmkl_blacs_openmpi_lp64.a,libmkl_gf_lp64.a,libmkl_sequential.a,libmkl_core.a,libgfortran.a] --with-scalapack=1 --with-shared-libraries=1 --with-windows-graphics=0 --with-x=0 --with-amgx=1 --download-amgx=1 -CUDAC=nvcc --with-cxx=/p/software/juwelsbooster/stages/2020/software/OpenMPI/4.1.1-GCC-10.3.0/bin/mpic++ --with-fc=/p/software/juwelsbooster/stages/2020/software/OpenMPI/4.1.1-GCC-10.3.0/bin/mpifort --with-cc=/p/software/juwelsbooster/stages/2020/software/OpenMPI/4.1.1-GCC-10.3.0/bin/mpicc --prefix=/some/non-root-dir`

Accordingly, we are using GCC-10.3, OpenMPI-4.1.1 (with CUDA-support) and CUDA/11.3. While executing "make" on AmgX, the configuration process of PETSc failed.

After tracing the error back, we finally found the following reason:
 
```
20 errors detected in the compilation of "/p/project/prpb100/COMMON/petsc_amgx_src/arch-linux-c-opt/externalpackages/git.amgx/core/src/aggregation/coarseAgenerators/low_deg_coarse_A_generator.cu".
-- Removing /p/project/prpb100/COMMON/petsc_amgx_src/arch-linux-c-opt/externalpackages/git.amgx/petsc-build/core/CMakeFiles/amgx_core.dir/src/aggregation/coarseAgenerators/./amgx_core_generated_low_deg_coarse_A_generator.cu.o
/p/project/prpb100/COMMON/petsc_amgx_src/arch-linux-c-opt/bin/cmake -E rm -f /p/project/prpb100/COMMON/petsc_amgx_src/arch-linux-c-opt/externalpackages/git.amgx/petsc-build/core/CMakeFiles/amgx_core.dir/src/aggregation/coarseAgenerators/./amgx_core_generated_low_deg_coarse_A_generator.cu.o
CMake Error at amgx_core_generated_low_deg_coarse_A_generator.cu.o.Release.cmake:284 (message):
  Error generating file
  /p/project/prpb100/COMMON/petsc_amgx_src/arch-linux-c-opt/externalpackages/git.amgx/petsc-build/core/CMakeFiles/amgx_core.dir/src/aggregation/coarseAgenerators/./amgx_core_generated_low_deg_coarse_A_generator.cu.o
make[2]: *** [core/CMakeFiles/amgx_core.dir/build.make:3132: core/CMakeFiles/amgx_core.dir/src/aggregation/coarseAgenerators/amgx_core_generated_low_deg_coarse_A_generator.cu.o] Fehler 1
```
We could only resolve this problem after reverting the final commit to this repository by 

`git checkout f0d54767bc4ff96049872d994acf5e630312cd97`

The very same behavior could be reproduced when we tried to build a standalone (=not via PETSc) of the AmgX library: Again, only after using an earlier state of the code, the build worked.

It would be very kind if you could give us any hints concerning the mentioned problem. It may well be that we are making any mistakes while configuring... If required, we are happy to provide further information. Thank you in advance.

Best regards,

Simon

**Comment by mattmartineau** [comment]
I have a feeling this may be an issue that occurs when building with CUDA 10.x and then compiling without passing the CUDA_ARCH flag - could you confirm the cmake line you used for AmgX?

The most recent commit seems to have broken the case where SM35, SM50, or SM60 is compiled for, which is part of the default set (35 50 60 70) if you pass no CUDA_ARCH flag for CUDA 10.x. I am planning to release a significant update to the build soon which will include a fix, but for now I'm hoping you should be able to pass, e.g. CUDA_ARCH=70, or whatever makes sense given the architecture of the card you are planning to run on.

**Comment by swenczowski** [comment]
Thank you very much for the quick response.

I can confirm that I did not specify any CUDA_ARCH when trying to build AmgX. I plainly used:

```
mkdir build
cd build
cmake ..
make -j 4
make install
```

I will give it a try with CUDA_ARCH as soon as possible and report the findings.

**Comment by mattmartineau** [comment]
Awesome. The most recent commit updated some of the code paths for sm70, but not sm35. When you compile without the CUDA_ARCH flag on CUDA 10.x it tries to compile with sm35, sm50, sm60, and sm70. The smXX < sm70 fail to compile, hence the error you saw.

I'll release a patch soon that makes the old sm35 - sm60 code paths work the same way as the new path, although they're actually headed for deprecation soon anyway! We are working on CI internally so small issues like this will magically disappear soon ;)
