### ISSUE TITLE
Why is `-static-libgcc` enforced?

### ISSUE THREAD

**Issue by stgeke** [NVIDIA/AMGX#171]
https://github.com/NVIDIA/AMGX/blob/main/CMakeLists.txt#L81

**Comment by marsaev** [comment]
This is artifact from the past where we've tried to reduce number of dependencies for the binary. I don't think AMGX needs this now, especially if you plan to run binary on the same system as it was compiled on.

**Comment by mattmartineau** [comment]
Thanks for pointing out - I'll remove in a future pull request.

**Comment by mattmartineau** [comment]
Removed in main. Thank you for pointing it out.
