### ISSUE TITLE
make error. how to recompile with fPIC

### ISSUE THREAD

**Issue by ztdepztdep** [NVIDIA/AMGX#174]
`/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/amgx_libs.dir/base/src/distributed/distributed_io.cu.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/amgx_libs.dir/base/src/distributed/distributed_manager.cu.o: relocation R_X86_64_32 against symbol `_ZN4amgx32map_col_indices_and_count_rowlenILi4EEEvPiS1_S1_S1_ii' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/amgx_libs.dir/base/src/eigensolvers/eigensolver.cu.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/amgx_libs.dir/base/src/eigensolvers/eigenvector_solver.cu.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/amgx_libs.dir/base/src/energymin/interpolators/em_interpolator.cu.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/amgx_libs.dir/base/src/energymin/selectors/em_selector.cu.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/amgx_libs.dir/base/src/error.cu.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/amgx_libs.dir/base/src/gaussian_elimination.cu.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/amgx_libs.dir/base/src/global_thread_handle.cu.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/amgx_libs.dir/base/src/hash_workspace.cu.o: relocation R_X86_64_32S against symbol `_ZTVN4amgx14Hash_WorkspaceINS_14TemplateConfigIL16AMGX_MemorySpace1EL17AMGX_VecPrecision0EL17AMGX_MatPrecision0EL17AMGX_IndPrecision2EEEiEE' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/amgx_libs.dir/base/src/logger.cu.o: relocation R_X86_64_32 against `.nvFatBinSegment' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/amgx_libs.dir/base/src/matrix.cu.o: relocation R_X86_64_32S against symbol `_ZZN3cub26GetPerDeviceAttributeCacheINS_18PtxVersionCacheTagEEERNS_23PerDeviceAttributeCacheEvE5cache' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/amgx_libs.dir/base/src/matrix_coloring/matrix_coloring.cu.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/amgx_libs.dir/base/src/matrix_io.cu.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/amgx_libs.dir/base/src/memory_info.cu.o: relocation R_X86_64_32 against `.nvFatBinSegment' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/amgx_libs.dir/base/src/misc.cu.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/amgx_libs.dir/base/src/multiply.cu.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/amgx_libs.dir/base/src/norm.cu.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/amgx_libs.dir/base/src/profile.cu.o: relocation R_X86_64_32 against symbol `_Z21profileLevelUp_kernelv' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/amgx_libs.dir/base/src/resources.cu.o: relocation R_X86_64_32 against symbol `_ZSt4cout@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/amgx_libs.dir/base/src/scalers/scaler.cu.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/amgx_libs.dir/base/src/solvers/algebraic_multigrid_solver.cu.o: relocation R_X86_64_32S against symbol `_ZTVN4amgx25AlgebraicMultigrid_SolverINS_14TemplateConfigIL16AMGX_MemorySpace0EL17AMGX_VecPrecision0EL17AMGX_MatPrecision0EL17AMGX_IndPrecision2EEEEE' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/amgx_libs.dir/base/src/solvers/dummy_solver.cu.o: relocation R_X86_64_32S against symbol `_ZTVN4amgx12Dummy_SolverINS_14TemplateConfigIL16AMGX_MemorySpace0EL17AMGX_VecPrecision0EL17AMGX_MatPrecision0EL17AMGX_IndPrecision2EEEEE' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/amgx_libs.dir/base/src/solvers/solver.cu.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/amgx_libs.dir/base/src/sort.cu.o: relocation R_X86_64_32 against symbol `_ZN3cub31DeviceRadixSortSingleTileKernelINS_21DeviceRadixSortPolicyImNS_8NullTypeEiE9Policy800ELb0EmS2_iEEvPKT1_PS5_PKT2_PS9_T3_ii' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/amgx_libs.dir/base/src/thread_manager.cu.o: relocation R_X86_64_32 against `.nvFatBinSegment' can not be used when making a shared object; recompile with -fPIC
`

**Comment by marsaev** [comment]
What are your CUDA toolkit, host compiler and cmake versions? Can you provide CMake output?

**Comment by mattmartineau** [comment]
Could you also try doing a fresh build. Delete the build directory, recreate, run cmake, make, etc.

I have in the past seen errors like this show up and a fresh build resolved them.

**Comment by stgeke** [comment]
It may be related to https://github.com/NVIDIA/AMGX/issues/171

**Comment by ztdepztdep** [comment]
> Could you also try doing a fresh build. Delete the build directory, recreate, run cmake, make, etc.
> 
> I have in the past seen errors like this show up and a fresh build resolved them.

Thanks, it works.
