### ISSUE TITLE
what is the meaning of the warning. "Cannot read file as JSON object, trying as AMGX config"

### ISSUE THREAD

**Issue by ztdepztdep** [NVIDIA/AMGX#175]
Cannot read file as JSON object, trying as AMGX config
Converting config string to current config version
Parsing configuration string: selector=AGGRESSIVE_HMIS ; 
Cannot read file as JSON object, trying as AMGX config
Cannot read file as JSON object, trying as AMGX config
Converting config string to current config version
Parsing configuration string: interpolator=MULTIPASS ;

**Comment by marsaev** [comment]
It is benign, sorry for confusion. Any config related API tries to parse input as a JSON first and prints the message if fails to do so.
