### ISSUE TITLE
error: On entry to cusparseCreateDnVec() parameter number 3 (values) had an illegal value: NULL pointer

### ISSUE THREAD

**Issue by ztdepztdep** [NVIDIA/AMGX#194]
On entry to cusparseCreateDnVec() parameter number 3 (values) had an illegal value: NULL pointer
Caught amgx exception: CUSPARSE_STATUS_INVALID_VALUE
 at: /home/ztdep/Downloads/AMGX/base/src/amgx_cusparse.cu:1030
Stack trace:

I upload my matrix with `AMGX_matrix_upload_all` , but I obtained the error. Could you please give me some suggestions? 
the system can be solved sucessfully with amgx read system.

**Comment by ztdepztdep** [comment]
> Could you please share a reproducer?

I found the problem. The x and b should be uploaded too.

**Comment by mattmartineau** [comment]
Great - thanks for the update. Glad you found the answer.
