### ISSUE TITLE
Caught amgx exception: Cannot allocate pinned memory?

### ISSUE THREAD

**Issue by ztdepztdep** [NVIDIA/AMGX#198]
I just update my cuda from 11.3 to 11.7, and I met the following error. I have tried recompiling the AMGX, but it still happening. 
Could you please give me some suggestions?

Compiled with CUDA Runtime 11.7, using CUDA driver 11.5
Caught amgx exception: Cannot allocate pinned memory
 at: /home/ztdep/Downloads/AMGX/base/src/global_thread_handle.cu:374
Stack trace:
 /home/ztdep/lib/AMGX/lib/libamgxsh.so : amgx::memory::PinnedMemoryPool::PinnedMemoryPool()+0xe6
 /home/ztdep/lib/AMGX/lib/libamgxsh.so : amgx::allocate_resources(unsigned long, unsigned long, unsigned long, unsigned long, unsigned long)+0x3b
 /home/ztdep/lib/AMGX/lib/libamgxsh.so : amgx::Resources::Resources(amgx::AMG_Configuration*, void*, int, int const*)+0xb7e
 /home/ztdep/lib/AMGX/lib/libamgxsh.so : AMGX_resources_create_simple()+0x8d

**Comment by marsaev** [comment]
Please, try with latest revision of `master` branch

**Comment by xiaorong117** [comment]
hello, the probelm is solved? i met this today.  My program goes well days ago, but todat this exception comes... help help help sos

**Comment by ztdepztdep** [comment]
> hello, the probelm is solved? i met this today. My program goes well days ago, but todat this exception comes... help help help sos

Hi, I recompiled it.
