### ISSUE TITLE
An (indirect) issue from Fraunhofer-Chalmers Centre: CUDA 9.0/9.1

### ISSUE THREAD

**Issue by bnase** [NVIDIA/AMGX#20]
@marsaev Me and @niklaskarla had been having great performance issues with cusparse< type >csrsv_analysis in CUDA 9.0 and CUDA 9.1. It is 20 times slower than in CUDA 8.0, just running the same Sample code conjugateGradientPrecond on same GPU for a matrix sufficiently large enough.

We know it is not AMGX related (from what I can see that specific function is not being called anywhere in AMGX), but since having a Windows AMGX requires CUDA 9.0+, this enforces us to use those versions. Is it a known bug? Could we direct it to the cuSparse API group?

**Comment by marsaev** [comment]
Hi @bnase ,

Whoa, 20x difference is definitely something wrong. You should create a question in the NVIDIA devtalks forum: https://devtalk.nvidia.com/default/board/55/gpu-accelerated-libraries/ , and provide more info like GPU used, sizes of input (preferably input itself), repro steps - questions will be forwarded to appropriate team.

**Comment by bnase** [comment]
@marsaev thanks, hopefully your colleagues will notice the post! Just FYI:
[https://devtalk.nvidia.com/default/topic/1030432/gpu-accelerated-libraries/cusparse-performance-issue-after-cuda-toolkit-9-0-cusparse-lt-t-gt-csrsv_analysis-20-times-slower/](url)

**Comment by marsaev** [comment]
Thanks for reporting a bug! I'll close this issue.
