### ISSUE TITLE
The GMRES solver stop the iteration at tolerance of 1E-11. 

### ISSUE THREAD

**Issue by ztdepztdep** [NVIDIA/AMGX#200]
I found that the GMRES solver stops the iteration at the tolerance of 1E-11, since I set the tolerance as 1E-15 and a maxiters of 1500. Why  the solver can't iterate further? 
    At this tolerance error, the solution has an L2 error of 1E-4 compared with the exact solution. While, with Trilinos packages, the solution can reach a tolerance of 1E-14, and the L2 error is 1E-9 compared with the exact solution.
  The difference between the Trilinos package only exists when the matrix size becomes larger and larger. 
Could you please give me some suggestions? 

      679              1.4540   3.209150e-11         0.9802
            680              1.4540   3.160799e-11         0.9849
-             681              1.4540   3.116502e-11         0.9860
-             682              1.4540   3.051489e-11         0.9791
-             683              1.4540   2.965427e-11         0.9718
-             684              1.4540   2.860530e-11         0.9646
-             685              1.4540   2.761962e-11         0.9655
-             686              1.4540   2.662535e-11         0.9640
-             687              1.4540   2.523402e-11         0.9477
-             688              1.4540   2.442717e-11         0.9680
-             689              1.4540   2.357364e-11         0.9651
-             690              1.4540   2.272572e-11         0.9640
-             691              1.4540   2.202386e-11         0.9691
-             692              1.4540   2.146497e-11         0.9746
-             693              1.4540   2.106082e-11         0.9812
-             694              1.4540   2.079263e-11         0.9873
-             695              1.4540   2.052893e-11         0.9873
-             696              1.4540   2.012205e-11         0.9802
-             697              1.4540   1.975104e-11         0.9816
-             698              1.4540   1.948999e-11         0.9868
-             699              1.4540   1.910927e-11         0.9805
-             700              1.4540   1.882346e-11         0.9850
-             701              1.4540   1.862454e-11         0.9894
-             702              1.4540   1.845032e-11         0.9906
-             703              1.4540   1.825542e-11         0.9894
-             704              1.4540   1.809315e-11         0.9911
-             705              1.4540   1.788551e-11         0.9885
-             706              1.4540   1.755795e-11         0.9817
-             707              1.4540   1.718144e-11         0.9786
-             708              1.4540   1.667965e-11         0.9708
-          --------------------------------------------------------------
-          Total Iterations: 709
- `
- 
{
-     "config_version": 2, 
-     "solver": {
-         "preconditioner": {
-             "interpolator": "D2", 
-             "solver": "AMG", 
-             "print_grid_stats": 1, 
-             "aggressive_levels": 2, 
-             "interp_max_elements": 4, 
-             "smoother": {
-                 "relaxation_factor": 1.5, 
-                 "scope": "jacobi", 
-                 "solver": "JACOBI_L1"
-             }, 
-             "presweeps": 2, 
-             "selector": "HMIS", 
-             "coarsest_sweeps": 2, 
-             "coarse_solver": "NOSOLVER", 
-             "max_iters": 1, 
-             "max_row_sum": 0.9, 
-             "strength_threshold": 0.15, 
-             "min_coarse_rows": 2, 
-             "scope": "amg_solver", 
-             "max_levels":1, 
-             "cycle": "V", 
-             "postsweeps": 2
-         },   
-         "print_grid_stats": 1, 
-         "store_res_history": 1, 
-         "solver": "GMRES", 
-         "print_solve_stats": 1, 
-         "obtain_timings": 0, 
-         "max_iters": 1500, 
-         "monitor_residual": 1, 
-         "gmres_n_restart": 20, 
-         "convergence": "RELATIVE_INI_CORE", 
-         "tolerance": 1e-15, 
-         "norm": "L2"
-      }
- }

**Comment by marsaev** [comment]
> `"convergence": "RELATIVE_INI_CORE", `
means relative to the initial residual at iteration 0. Set it to `ABSOLUTE` is you want iterate until absolute value of residual norm

**Comment by ztdepztdep** [comment]
> 

I noticed the promise about " the relative error has reached the machine precision" , but what is the difference between the Trilinos and AMGX gmres solver, since it gave different error level compared with the exact solutoin.
