### ISSUE TITLE
[Question] How cusparse APIs are used in AMGx

### ISSUE THREAD

**Issue by Soujanyajanga** [NVIDIA/AMGX#204]
Can you please let us know how cusparse API are getting leveraged by AMGx.
Specifically what configurations (condition/criteria) needs to be met in the code flow for AMGx to use cusparse APIs.

Can you please recommend any specific test case that can be studied to understand the flow.

**Comment by mattmartineau** [comment]
We use SpGEMM and SpMV extensively. I would recommend amgx_mpi_poisson7 as the simplest test case to do some profiling with.

**Comment by marsaev** [comment]
@Soujanyajanga, let me know if we answered your question or you need more details

**Comment by Soujanyajanga** [comment]
> @Soujanyajanga, let me know if we answered your question or you need more details

Yes, you answered my question. This can be closed.
