### ISSUE TITLE
0 iterations on C++ but works fine on example app

### ISSUE THREAD

**Issue by jjcasmar** [NVIDIA/AMGX#217]
I am trying to use AMGX to solve my simulation system of equations. I am building the problem using Eigen and I have done the proper conversions to pass the data to AMGX. My code is the following:

```
        Eigen::SparseMatrix<float> A; // It comes from somewhere
        A.makeCompressed();  // Ensure it is CSR
        dv = cg.solve(rhs_op).cast<de::Real>(); // Just for comparison purposes

        // Save matrix to disk so I can check with the example app
        Eigen::saveMarket(A, "A.mtx");
        Eigen::saveMarketVector(rhs, "b.mtx");
        Eigen::saveMarketVector(dv, "x.mtx");

        {
            AMGX_initialize();

            checkAMGX(AMGX_config_create_from_file(&config, "/workspace/3rdparty/PCG_NOPREC.json"));
            checkAMGX(AMGX_resources_create_simple(&rsrc, config));
            checkAMGX(AMGX_matrix_create(&matrix, rsrc, AMGX_mode_dFFI));
            checkAMGX(AMGX_vector_create(&amrhs, rsrc, AMGX_mode_dFFI));
            checkAMGX(AMGX_vector_create(&soln, rsrc, AMGX_mode_dFFI));
            checkAMGX(AMGX_solver_create(&solver, rsrc, AMGX_mode_dFFI, config));
            de::VectorXf dvF(totalNbDoF);

            checkAMGX(AMGX_matrix_upload_all(matrix,
                                             static_cast<int>(totalNbDoF),
                                             static_cast<int>(A.nonZeros()),
                                             1,
                                             1,
                                             A.outerIndexPtr(),
                                             A.innerIndexPtr(),
                                             A.valuePtr(),
                                             nullptr));
            checkAMGX(AMGX_vector_upload(amrhs, static_cast<int>(totalNbDoF), 1, rhs_op.data()));

            checkAMGX(AMGX_solver_setup(solver, matrix));
            checkAMGX(AMGX_solver_solve_with_0_initial_guess(solver, amrhs, soln));

            checkAMGX(AMGX_vector_download(soln, dvF.data()));
            AMGX_SOLVE_STATUS status;
            AMGX_solver_get_status(solver, &status);
            checkAMGXSolve(status);
            dv = dvF.cast<de::Real>();
        }
```

Using this code, I get 0 iterations. I have double checked everything, and apparently, the data is correctly uploaded, because the final residual I get is the one I get if I just do `(Ax - b).norm()` with a initial guess of 0. 

I have also tested the example app (adapting the A.mtx file so it contains the rhs vector) `./examples/amgx_capi -m ../../../build/release/bin/A.mtx -c ../../PCG_NOPREC.json` and it works fine, so my system is working correctly. 

Any hints what could be wrong?

**Comment by marsaev** [comment]
Can you try "binding" vectors objects to the matrix objects like in the example: https://github.com/NVIDIA/AMGX/blob/main/examples/amgx_mpi_capi_agg.c#L504-L505

**Comment by jjcasmar** [comment]
Still fails in the same way

**Comment by jjcasmar** [comment]
So apparently my issue is some weird interaction between rapidjson. I use rapidjson in my main application and AMGX uses another version of rapidjson. 

I think the linker is getting confused and when is triers to parse the json config file, its calling some functions from AMGX rapidjson, but then, at some points, it tries to use a function from my application rapidjson copy. 

I have tried to remove AMGX version of rapidjson, but apparently its too old and it doesn't compile with newer versions. I guess I am out of look, I will have to use non json config files

Ill close as its not an AMGX issue
