### ISSUE TITLE
Problem compiling my program

### ISSUE THREAD

**Issue by BeneBr** [NVIDIA/AMGX#22]
Hi guys, i am trying compiling my simple program usign AMGX. But when i try, initialize the AMGX, e.g:

#include<"Amgx_c.h">

main(){

AMGX_initialize()
}

I have one error, "Undefined reference to AMGX_initialize".

What happens?
Best regards.

**Comment by marsaev** [comment]
Did you link amgx library?

**Comment by BeneBr** [comment]
I dont know. I only include de .h on header of my file.

**Comment by BeneBr** [comment]
How i link the library?

**Comment by marsaev** [comment]
What do you use yo build your program?

**Comment by BeneBr** [comment]
The program was build sucefull. During the compilling some warning appears, but dont occurs errors.

**Comment by BeneBr** [comment]
The problem occur when i create my program file. No when i compile the AMGX.

**Comment by marsaev** [comment]
> How i link the library?
It depends on your toolchain. What do you use to build your program?

**Comment by BeneBr** [comment]
I follow the steps of README file for build the program.

**Comment by marsaev** [comment]
You are under linux and you are using gcc am i right?
1. Were you able to build the AMGX library? 
2. Have you tried to build an example?

**Comment by BeneBr** [comment]
1. Yes.
2. Yes.

**Comment by marsaev** [comment]
Ok, then just add '**-lamgxsh -L/path/to/library/build**' to the command line that builds your program.

**Comment by BeneBr** [comment]
The library is the amgx_c.h?

**Comment by marsaev** [comment]
Library is libamgxsh.so - is an artifact of AMGX build.

**Comment by BeneBr** [comment]
My program nedd stay on the same folder of AMGX.

**Comment by marsaev** [comment]
Have you tried add command line flags i have suggested in https://github.com/NVIDIA/AMGX/issues/22#issuecomment-373358348

**Comment by BeneBr** [comment]
gcc -o test test.c -libamgxsh -L/home/gustavo/Documents/CUda/AMGX-master/build/

**Comment by BeneBr** [comment]
I can´t link my library, i pass the comnand above, but when i execute my programa, they dont run.

**Comment by BeneBr** [comment]
I solved my problem with this link: 
https://www.cprogramming.com/tutorial/shared-libraries-linux-gcc.html

**Comment by marsaev** [comment]
Great!
I'll close the issue.
