### ISSUE TITLE
GTC 2018 Anyone? (this is not an issue)

### ISSUE THREAD

**Issue by AndreaNES** [NVIDIA/AMGX#24]
Hi,
is anyone from the develpers team or any user at GTC 2018 in San Jose?

I would be interested in meeting developers / other users to understand better the road-map of AMGX and share experiences in the use of AMGX.

Best Regards,

Andrea Borsic

**Comment by marsaev** [comment]
Hey @AndreaNES ,
You might find some people in the pod sessions - Harun Bayraktar should be able to answer to some of your questions - I can send his contact to your email. We would also glad to hear your feedback.

Thanks,

**Comment by AndreaNES** [comment]
Hi, thanks for coming back to my post. I forgot to provide my contact in the fist place. I can be contacted at aborsic@ne-scientific.com I would be glad to be in touch and possibly meet with Harun.

Best,

Andrea
