### ISSUE TITLE
Openfoam Matrix

### ISSUE THREAD

**Issue by BeneBr** [NVIDIA/AMGX#25]
Hi guys, how i convert one mesh matrix of openfoam to a matrix market for AMGX?

**Comment by BeneBr** [comment]
Yes, i read this article, but is not clear for me. I would like the one use case of openfoam with amgx. Ty.

**Comment by marsaev** [comment]
MatrixMarket is an open format of storage: https://math.nist.gov/MatrixMarket/formats.html
On the mentioned webpage there are also I/O examples for MatrixMarket format in C/fortran/python.
Yes, i know there are interfaces to AMGX for OpenFOAM, but i think you'll get more luck on the OpenFOAM forums. Let me know if you find something i can share in the readme!

Thanks,

**Comment by BeneBr** [comment]
I read about MM, and i am tryng converte one openfoam matrix to a matrix market for using in amgx. Thank you very much for your support.
