### ISSUE TITLE
Compute capability 2.0?

### ISSUE THREAD

**Issue by shwina** [NVIDIA/AMGX#29]
Would AMGX support GPUs with compute capability 2.0? I see [this PR](https://github.com/NVIDIA/AMGX/pull/15/) by @niklaskarla (edit - apologies for tagging the wrong user ID)  adds support for devices with 3.0. Wondering if a similar fix could accommodate lower CC?

**Comment by marsaev** [comment]
Hi,

We are actually advising on doing quite opposite - dropping 2.0 support. Starting with CUDA 9.0 (and corresponding r384.xx driver) SMs 2.x devices support is dropped.

**Comment by shwina** [comment]
Thanks for the information! Perhaps something like the following could be added to the README?

> AmgX runs on GPUs that support compute capability >= 3.0. Check to see if your GPU supports this [here](https://developer.nvidia.com/cuda-gpus).

**Comment by marsaev** [comment]
Thanks,

I've added mention of 3.0 CC requirement to the README
