### ISSUE TITLE
An issue from Fraunhofer-Chalmers Centre: amgx_capi_multi

### ISSUE THREAD

**Issue by bnase** [NVIDIA/AMGX#3]
@marsaev 
@lukeyeager 

Running amgx_capi_multi example with n=2, on a machine with two identical GPUs, produces (after the 1st solve is completed)

`Caught amgx exception: Could not create the CUDENSE handle`

**Comment by marsaev** [comment]
Hi @bnase ,

Can you, please, provide full command line and log for your run? 

Thanks,

**Comment by bnase** [comment]
Hello @marsaev. Per your request:
https://pastebin.com/z0qfKZd1

Keep in mind I haven't used -n flag but I set it int n=2; in the source file.

**Comment by marsaev** [comment]
You are running './amgx_capi_multi', what example (source file) is that? This binary is not built by default.
What exactly do you want to achieve? We support multi-GPU only using MPI and process is typically run by 'mpirun'.

**Comment by bnase** [comment]
@marsaev the source file is: https://github.com/NVIDIA/AMGX/blob/master/examples/amgx_capi_multi.c, which I used to test the possibility of
A) initialising AMGX, 
B) solving a matrix GPU ID 1,
C) solving another on GPU ID 0, then 
D) finalize AMGX.
It is in the spirit of "Single thread, multi-GPU paragraph in AMGX API reference", with the main difference that instead of using a single constructor with int devices[]={0,1} one spawns, then in serial, first for int devices1[]={0} then for int devices2[]={0}. That is precisely what amgx_capi_multi.c seems to be doing!
What am I missing?

**Comment by marsaev** [comment]
@bnase 
This kind of usage should be fine and i was able to reproduce this crash. Looks like some kind of information is being reused across solvers, most likely from memory manager, need to looks at this more closely. Thanks for reporting this, single thread - multiple GPUs case was not a priority for the project (application you have mentioned is not included in the building process or any testing).

**Comment by bnase** [comment]
@marsaev 
Thanks a lot, happy to be useful, trust me there is plenty of room for applications of the single thread/multiple GPU! We'd love to showcase some, when the issue is solved :) Keep us in the loop.

**Comment by marsaev** [comment]
While working on this issue i stumbled upon a lot of other problems in the code, so i decided to go step by step. 
I should say that out code is not thread safe, however it's not impossible to introduce thread safety - key points here are proper handling of cuda libraries handles (cublas, cusparse and cusolver) and memory manager via thread-specific resource object.
I will shortly submit change to the library for proper handling of managing resources via resource object which will fix amgx_capi_multi example which sequentially calls different solvers bound to different GPUs (no overlap between API calls).
Next step would be making whole library thread safe by reviewing the rest of the code (i.e. supplying resource specific CUDA libraries handles to the libraries' calls and reviewing any static data).

**Comment by bnase** [comment]
@marsaev thanks! It's good to know the issues are not our own shortcomings!

**Comment by marsaev** [comment]
Related issue: https://github.com/NVIDIA/AMGX/issues/21 , work in progress would be tracked there
