### ISSUE TITLE
Error trying to build an app that uses AmgX

### ISSUE THREAD

**Issue by gaaraujo** [NVIDIA/AMGX#301]
Hi, I am trying to build an app that uses the AmgX library. I managed to compile AmgX successfully. However, I get errors when trying to compile an app that uses AmgX. The source code for this app is inside a folder `src`, with the main file being `gifted.cu`

To build this app, I use the following Makefile
[makefile.txt](https://github.com/NVIDIA/AMGX/files/14564006/makefile.txt)

That basically results in the following command being executed:
`/share/software/user/open/cuda/12.2.0/bin/nvcc src/gifted.cu -o gifted -Isrc -I"/share/software/user/open/cuda/12.2.0/include"  -I"../amgx/include" -I"../amgx/thrust" -lcudart -L"/share/software/user/open/cuda/12.2.0/lib64" -lamgxsh -L"../amgx/build" -Xlinker "-rpath="./lib" " -ldl  `

Part of the output I get is the following:
```
/share/software/user/open/cuda/12.2.0/bin/nvcc src/gifted.cu -o gifted -Isrc -I"/share/software/user/open/cuda/12.2.0/include"  -I"../amgx/include" -I"../amgx/thrust" -lcudart -L"/share/software/user/open/cuda/12.2.0/lib64" -lamgxsh -L"../amgx/build" -Xlinker "-rpath="./lib" " -ldl 
../amgx/include/cusp/memory.h(28): error: identifier "amgx" is undefined
      using host_memory = amgx::thrust::host_system_tag;
                          ^

../amgx/include/cusp/memory.h(28): error: expected a ";"
      using host_memory = amgx::thrust::host_system_tag;
                              ^

../amgx/include/cusp/memory.h(29): error: identifier "amgx" is undefined
      using device_memory = amgx::thrust::device_system_tag;
                            ^

../amgx/include/cusp/memory.h(29): error: expected a ";"
      using device_memory = amgx::thrust::device_system_tag;
                                ^

../amgx/include/cusp/memory.h(30): error: identifier "amgx" is undefined
      using any_memory = amgx::thrust::any_system_tag;
                         ^

../amgx/include/cusp/memory.h(30): error: expected a ";"
      using any_memory = amgx::thrust::any_system_tag;
                             ^

../amgx/include/vector_thrust_allocator.h(58): error: qualified name is not allowed
          typedef amgx::thrust::device_ptr<T> pointer;
                  ^

../amgx/include/vector_thrust_allocator.h(58): error: explicit type is missing ("int" assumed)
          typedef amgx::thrust::device_ptr<T> pointer;
```

Any idea of what I could be missing in my makefile?

**Comment by marsaev** [comment]
You should not include AMGX sources directly. When you build AMGX use `make install` and use provided install files (library and headers) for your application (https://github.com/NVIDIA/AMGX/blob/main/CMakeLists.txt#L286-L289)

**Comment by gaaraujo** [comment]
Hi, @marsaev! Thanks for your quick answer! Just to clarify:

I built AmgX using the following according to [README.md](https://github.com/NVIDIA/AMGX/blob/main/README.md) 
```
mkdir build
cd build
cmake ../
make -j16 all

```

Instead, should I do this?
```
mkdir build
cd build
cmake ../
make -j16 install

```

**Comment by gaaraujo** [comment]
Update:

I ran make install inside the build directory of amgx, and obtained a new lib folder containing libamgxsh.so.

My makefile now runs the following: 

`/share/software/user/open/cuda/12.2.0/bin/nvcc src/gifted.cu -o gifted -Isrc -I"/share/software/user/open/cuda/12.2.0/include" -I"../amgx/include" -lcudart -L"/share/software/user/open/cuda/12.2.0/lib64" -lamgxsh -L"../amgx/lib" -Xlinker "-rpath="./lib" " -ldl  `

Unfortunately, I still get the same error. What else could I be missing?

**Comment by marsaev** [comment]
Command line looks right. Just to clarify - your files, i.e. `gifted.cu` should include **only** `amgx_c.h` header. According to error it seems other AMGX might be included there. Can you check what you include in sources?

**Comment by gaaraujo** [comment]
Thanks again for replying!

Indeed, I had some references to other libraries. In one of the files, I had:

```
#include <cusp/csr_matrix.h>
#include <cusp/print.h>
```
Getting rid of these headers worked! Thanks!

**Comment by gaaraujo** [comment]
Closing the issue!
