### ISSUE TITLE
Solving a system with multiple right-hand sides

### ISSUE THREAD

**Issue by kevle** [NVIDIA/AMGX#34]
Is there currently a way to solve a system A*X=B, where X and B are not a single but multiple vectors, at once? The only part of the documentation I could find that approaches this topic talks about computing multiple right-hand sides in succession.
There certainly are some applications where prior knowledge of multiple right-hand side vectors b^i is given and computing the solution to them simultaneously could lead to efficieny gains.

**Comment by marsaev** [comment]
No, there is no such functionality as for now. I can see it as a possible future improvement of AMGX.

**Comment by marsaev** [comment]
Currently out of scope of AMGX.
