### ISSUE TITLE
Can't understand the indexing scheme of coefficient matrix-A in Poisson's eqn solver example

### ISSUE THREAD

**Issue by fiyanshu7** [NVIDIA/AMGX#39]
Hi! I am modifying the Poisson's equation solver example for incorporating variable coefficient Poisson's equation, however, I am unable to interpret the indexing scheme. 

**The precise issue is that according to my understanding for every grid-point in my original matrix _(for which I am solving the 5 point discretized 2D Poisson's equation)_, I should have 5 coefficients (which should be -1, -1, 4, -1 and -1), however, I find that the number of coefficients are varying from 2 to 5 for different grid-points.** 

In order to understand the example code before modifying it for variable coefficient case, I printed the grid-point index and its coefficient value for a simple case of 4x4 matrix with single CPU and GPU processor.
I ran the code as follows: 
`mpirun -np 1 examples/amgx_mpi_poisson5 -mode dDDI -p 4 4 -c ../core/configs/FGMRES_AGGREGATION_JACOBI.json`

The output is attached herewith.
[output.log](https://github.com/NVIDIA/AMGX/files/2395734/output.log)

The example code is also attached.
[amgx_mpi_poisson5pt.zip](https://github.com/NVIDIA/AMGX/files/2395745/amgx_mpi_poisson5pt.zip)

**Comment by marsaev** [comment]
From the top of my head i would guess it will depend on the boundary conditions

**Comment by fiyanshu7** [comment]
Thanks for the reply. Can you pls refer me to some documentation of this example or something.

**Comment by marsaev** [comment]
AMGX works with matrix as a black box solver and just tries to solve system of linear equations without any prior knowledge, so proper matrix assembly is on the library user.
There is no specific documentation for this example, but I would assume for the matrix in this example closest would be discretization of poissons equation with dirichlet boundary condition.
