### ISSUE TITLE
I can't compile this project by Cmake at all for many day and nights

### ISSUE THREAD

**Issue by ningjiafei** [NVIDIA/AMGX#41]
I triede many times, and can't get useful imformations from Internet.
system information: 
CUDA 10.0
Cmake  cmake-3.13.0-rc3-win64-x64
IDE VS 2017
TOOOOOOO many errors showed below! This made me MAD.

Found OpenMP_C: -openmp  
Found OpenMP_CXX: -openmp  
Found OpenMP: TRUE   
Could NOT find MPI_C (missing: MPI_C_LIB_NAMES MPI_C_HEADER_DIR MPI_C_WORKS) 
Could NOT find MPI_CXX (missing: MPI_CXX_LIB_NAMES MPI_CXX_HEADER_DIR MPI_CXX_WORKS) 
Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND) 
This is a MPI build:FALSE
CUDA_TOOLKIT_ROOT_DIR not found or specified
Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
Cuda libraries: CUDA_CUDART_LIBRARY-NOTFOUND
CMake Error at CMakeLists.txt:247 (STRING):
  STRING sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.

CUDA_TOOLKIT_ROOT_DIR not found or specified
Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
CUDA_TOOLKIT_ROOT_DIR not found or specified
Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_CUDART_LIBRARY (ADVANCED)
    linked by target "amgx" in directory D:/Users/HIT/Desktop/AMGX-master
    linked by target "amgxsh" in directory D:/Users/HIT/Desktop/AMGX-master
    linked by target "amgx_base" in directory D:/Users/HIT/Desktop/AMGX-master/base
    linked by target "amgx_core" in directory D:/Users/HIT/Desktop/AMGX-master/core
    linked by target "amgx_template_plugin" in directory D:/Users/HIT/Desktop/AMGX-master/template_plugin
    linked by target "amgx_eigensolvers" in directory D:/Users/HIT/Desktop/AMGX-master/eigensolvers
    linked by target "generate_poisson" in directory D:/Users/HIT/Desktop/AMGX-master/examples
    linked by target "generate_poisson7_dist_renum" in directory D:/Users/HIT/Desktop/AMGX-master/examples
    linked by target "amgx_tests_library" in directory D:/Users/HIT/Desktop/AMGX-master/tests
    linked by target "amgx_tests_launcher" in directory D:/Users/HIT/Desktop/AMGX-master/tests
CUDA_TOOLKIT_INCLUDE (ADVANCED)
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master/base
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master/base
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master/core
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master/core
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master/core
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master/template_plugin
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master/template_plugin
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master/eigensolvers
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master/eigensolvers
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master/examples
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master/examples
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master/examples
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master/examples
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master/examples
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master/examples
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master/examples
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master/examples
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master/eigen_examples
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master/eigen_examples
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master/eigen_examples
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master/eigen_examples
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master/tests
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master/tests
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master/tests
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master/tests
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master/tests
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master/tests
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master/tests
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master/tests
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master/tests
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master/tests
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master/tests
   used as include directory in directory D:/Users/HIT/Desktop/AMGX-master/tests
cublas_library
    linked by target "amgx" in directory D:/Users/HIT/Desktop/AMGX-master
    linked by target "amgxsh" in directory D:/Users/HIT/Desktop/AMGX-master
cusolver_library
    linked by target "amgx" in directory D:/Users/HIT/Desktop/AMGX-master
    linked by target "amgxsh" in directory D:/Users/HIT/Desktop/AMGX-master
    linked by target "generate_poisson" in directory D:/Users/HIT/Desktop/AMGX-master/examples
    linked by target "generate_poisson7_dist_renum" in directory D:/Users/HIT/Desktop/AMGX-master/examples
cusparse_library
    linked by target "amgx" in directory D:/Users/HIT/Desktop/AMGX-master
    linked by target "amgxsh" in directory D:/Users/HIT/Desktop/AMGX-master
    linked by target "generate_poisson" in directory D:/Users/HIT/Desktop/AMGX-master/examples
    linked by target "generate_poisson7_dist_renum" in directory D:/Users/HIT/Desktop/AMGX-master/examples
    linked by target "amgx_tests_launcher" in directory D:/Users/HIT/Desktop/AMGX-master/tests

Configuring incomplete, errors occurred!
See also "D:/Users/HIT/Desktop/AMGX-master/build/CMakeFiles/CMakeOutput.log".

 Your's 
Ning

**Comment by nrhamm17** [comment]
Is your path set correctly? It looks like CMAKE can't find your toolkit. Let me know if you get this working. I've been trying for hours to build this with the same configuration with no luck

**Comment by ningjiafei** [comment]
I have set path but I can't sure that is complete. It seem that CMAKE can't find something about MPI and CUDA.
CUDA_PATH_V10_0 = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
CUDA_PATH = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
MSMPI_BIN = C:\Program Files\Microsoft MPI\Bin\

**Comment by ningjiafei** [comment]
Here is another question that why every folder has a CMAKELIST.TXT？ Does that indicate that every folder could be compile  separately?

**Comment by Doublove** [comment]
The error "CMake Error at CMakeLists.txt:247 (STRING):" means cmake didn't select any CUDA toolkit version because you only installed CUDA10.0 when the cmake only got 9.x max. I found one solution to write your own CUDA toolkit version's cmake just by changing the 9 to 10.

**Comment by ningjiafei** [comment]
for the error :
 CMake Error at CMakeLists.txt:247 (STRING):
STRING sub-command REGEX, mode REPLACE needs at least 6 arguments total to
command.
I change the command 247
from 
STRING(REGEX REPLACE " " ";" CUDA_ARCH ${CUDA_ARCH})
to
STRING(REGEX REPLACE " " ";" CUDA_ARCH $"{CUDA_ARCH}")

AND setup the MPICH2 
 Now I compile AMGX with camke successfully .

**Comment by ningjiafei** [comment]
> The error "CMake Error at CMakeLists.txt:247 (STRING):" means cmake didn't select any CUDA toolkit version because you only installed CUDA10.0 when the cmake only got 9.x max. I found one solution to write your own CUDA toolkit version's cmake just by changing the 9 to 10.

OH I SEE!!! THANK YOU !!

**Comment by ningjiafei** [comment]
> The error "CMake Error at CMakeLists.txt:247 (STRING):" means cmake didn't select any CUDA toolkit version because you only installed CUDA10.0 when the cmake only got 9.x max. I found one solution to write your own CUDA toolkit version's cmake just by changing the 9 to 10.
“ write your own CUDA toolkit version's cmake just by changing the 9 to 10.”  build successfully,but the solution couldn't work. We may rewrite the CMakeLists.txt:242-244 that:
IF(CUDA_VERSION_MAJOR MATCHES 10)
  SET(CUDA_ARCH "35 52 60 75" CACHE STRING "Target Architectures (SM35 SM52 SM60 SM75), multiple are allowed")
ENDIF(CUDA_VERSION_MAJOR MATCHES 10)
