### ISSUE TITLE
calling a _host_ function from a _host_ _device_ function is not allowed

### ISSUE THREAD

**Issue by Doublove** [NVIDIA/AMGX#43]
I was using vs2015 update3 and cmake 3.13.1 to compile. After meeting the problem in [https://github.com/NVIDIA/AMGX/issues/36](url) and having solved the problem, I got another problem in building :

`1>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\include\thrust/detail/allocator/allocator_traits.inl(230): error : calling a __host__ function("std::_Iterator_base12::_Iterator_base12") from a __host__ __device__ function("std::_Iterator_base12::_Iterator_base12 [subobject]") is not allowed`
`1>`
`1>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\include\thrust/detail/allocator/allocator_traits.inl(230): error : calling a __host__ function("std::_Iterator_base12::~_Iterator_base12") from a __host__ __device__ function("std::_Iterator_base12::~_Iterator_base12 [subobject]") is not allowed`
`1>`
`1>  2 errors detected in the compilation of "C:/Users/i/AppData/Local/Temp/tmpxft_00005b44_00000000-10_comms_mpi_hostbuffer_stream.cpp1.ii".`
`1>  comms_mpi_hostbuffer_stream.cu`
`1>  CMake Error at amgx_base_generated_comms_mpi_hostbuffer_stream.cu.obj.Debug.cmake:283 (message):`
`1>    Error generating file`
`1>    C:/AMGX-master/build/base/CMakeFiles/amgx_base.dir/src/distributed/Debug/amgx_base_generated_comms_mpi_hostbuffer_stream.cu.obj`

**and** 

`2>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\include\thrust/system/cuda/detail/assign_value.h(78): error : calling a __host__ function("std::_Iterator_base12::_Iterator_base12") from a __host__ __device__ function("std::_Iterator_base12::_Iterator_base12 [subobject]") is not allowed`
`2>`
`2>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\include\thrust/system/cuda/detail/assign_value.h(78): error : calling a __host__ function("std::_Iterator_base12::~_Iterator_base12") from a __host__ __device__ function("std::_Iterator_base12::~_Iterator_base12 [subobject]") is not allowed`
`2>`
`2>  2 errors detected in the compilation of "C:/Users/i/AppData/Local/Temp/tmpxft_00002bd0_00000001-10_matrix_analysis.cpp1.ii".`
`2>  matrix_analysis.cu`
`2>  CMake Error at amgx_core_generated_matrix_analysis.cu.obj.Debug.cmake:283 (message):`
`2>    Error generating file`
`2>    C:/AMGX-master/build/core/CMakeFiles/amgx_core.dir/src/Debug/amgx_core_generated_matrix_analysis.cu.obj`

I was really confused that these errors occured in the CUDA thrust head files and I couldn't figure it out.
 I wonder if anyone else meets the same problem.

**Comment by Doublove** [comment]
Maybe I have got it solved. I rerun the building in profile mode, and the error occurred when building in debug mode just disappeared.

**Comment by ningjiafei** [comment]
You have to building it in release mode,but not debug mode

**Comment by marsaev** [comment]
There is known issue in the thrust/nvcc/msvc interaction in the debug mode. Unfortunately we will support only release on windows.
