### ISSUE TITLE
Question on AMGX configuration of published results.

### ISSUE THREAD

**Issue by bjorn2** [NVIDIA/AMGX#47]
Hi,
I have built AMGX and it works fine. For verification, I am trying to reproduce the results in Table 2 on page S618 in the article on AMGX by N.Naumov et.al. in SIAM J.Sci.Comput., vol 37, no.5, pp S602-S626 (2015). Trying different settings, but can not make the number of iterations agree (hardware is different so execution time will not agree) for any of the cases. It is not clear from the paper exactly which settings AMGX is using, if it is only AMG or AMG as preconditioner to another iterative method ? Is there by any chance a configuration file available for those runs ?
Best Regards
Bjorn

**Comment by ningjiafei** [comment]
> Hi,
> I have built AMGX and it works fine. For verification, I am trying to reproduce the results in Table 2 on page S618 in the article on AMGX by N.Naumov et.al. in SIAM J.Sci.Comput., vol 37, no.5, pp S602-S626 (2015). Trying different settings, but can not make the number of iterations agree (hardware is different so execution time will not agree) for any of the cases. It is not clear from the paper exactly which settings AMGX is using, if it is only AMG or AMG as preconditioner to another iterative method ? Is there by any chance a configuration file available for those runs ?
> Best Regards
> Bjorn

Could you tell me how long it cost you to compile AMG.sln? It cost me too much time and I don't know if my way wrong?
Just cmake ,then visual studio it ?

**Comment by davidherreroperez** [comment]
Hi bjorn2,

Were you able to reproduce the results of the paper? I'm interested in the results of Table 3, especially the number of iterations of CG-AMG.

Thanks

**Comment by marsaev** [comment]
If i recall correctly it was something along the lines of `core/configs/AMG_CLASSICAL_AGGRESSIVE_L1_TRUNC.json` configuration. If the question is still actual please reopen the issue and i can dig further
