### ISSUE TITLE
The DEBUG version couldn't be built due to "calling a __host__function from a __host__ __device__ function"

### ISSUE THREAD

**Issue by thrasher1985** [NVIDIA/AMGX#48]
The compiler I use is VS 2017, and the CUDA I use is CUDA 10. I have tried it on two computers, and I got the same errors every time.

The errors I get are:
calling a __host__ function("std::_Iterator_base12::_Iterator_base12") from a __host__ __device__ function("std::_Iterator_base12::_Iterator_base12 [subobject]") is not allowed	amgx_core	C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include\thrust\system\cuda\detail\assign_value.h

calling a __host__ function("std::_Iterator_base12::_Iterator_base12") from a __host__ __device__ function("std::_Iterator_base12::_Iterator_base12 [subobject]") is not allowed	amgx_core	C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include\thrust\system\cuda\detail\assign_value.h

By the way, it take me 4 to 6 hours to build amgx_core project with MPI. Would it be possible that I set up wrong somewhere?

**Comment by ningjiafei** [comment]
You must build it in RELEASE mode, and it's true that it will take hours

**Comment by marsaev** [comment]
See related #98
