### ISSUE TITLE
Build by vs2017, CUDA10.0   ERRORS

### ISSUE THREAD

**Issue by ningjiafei** [NVIDIA/AMGX#50]
I can,t solve it......
error	LNK1104	无法打开文件“D:\Users\HIT\Desktop\AMGX-master\build6\base\CMakeFiles\amgx_base.dir\src\Debug\amgx_base_generated_csr_multiply_sm20.cu.obj”	amgxsh	D:\Users\HIT\Desktop\AMGX-master\build6\LINK	1	

error		calling a __host__ function("std::_Iterator_base12::~_Iterator_base12") from a __host__ __device__ function("std::_Iterator_base12::~_Iterator_base12 [subobject]") is not allowed	amgx_base	C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include\thrust\system\cuda\detail\assign_value.h	78

**Comment by pyramidpoint** [comment]
Have you solved it yet?

**Comment by ningjiafei** [comment]
> Have you solved it yet?

yeah, I have solved it.

**Comment by marsaev** [comment]
Closing as seems the issue was resolved
