### ISSUE TITLE
Error building for Ubuntu 18.04.02 + CUDA  10.1.105-1

### ISSUE THREAD

**Issue by vmasyagin** [NVIDIA/AMGX#53]
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Found MPI_C: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so (found version "3.1") 
-- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
This is a MPI build:TRUE
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "10.1") 
Cuda libraries: /usr/local/cuda/lib64/libcudart_static.a-lpthreaddl/usr/lib/x86_64-linux-gnu/librt.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/victor/AMGX/build

Also use gcc and g++ version 4.8.5 without success.

During installation, multiple notifications appear and as a result, the build crashes:
/home/victor/AMGX/base/include/matrix.h:247:3646: note: in C++11 destructors default to noexcept
/home/victor/AMGX/base/include/matrix.h:247:4053: warning: throw will always call terminate() [-Wterminate]
                 cusparseCheckError(cusparseDestroyMatDescr(cuMatDescr));
/home/victor/AMGX/base/include/matrix.h:247:4053: note: in C++11 destructors default to noexcept
CMakeFiles/Makefile2:165: recipe for target 'base/CMakeFiles/amgx_base.dir/all' failed
make[1]: *** [base/CMakeFiles/amgx_base.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

A big request to help deal with the problem and build the library

**Comment by ningjiafei** [comment]
CUDA9.x is OK

**Comment by marsaev** [comment]
@vmasyagin 
I've tried to build with CUDA 10.1 and gcc 7.3 and saw similar output to yours. However note that you quoted warnings which are (more or less) benign. Actual error is:
> /home/marsaev/work/AMGX/core/src/classical/interpolators/distance2.cu(1448): error: identifier "sign" is undefined
similar to what is described in another issue: https://github.com/NVIDIA/AMGX/issues/59

I'll submit a quick fix for that

**Comment by marsaev** [comment]
Also forgot to mention this issue in https://github.com/NVIDIA/AMGX/commit/b6b93592158df07a8c84d49c0c39e36023b1dba4
Should be fixes now.
