### ISSUE TITLE
AMGx adapter in Trilinos/MueLu

### ISSUE THREAD

**Issue by svancri** [NVIDIA/AMGX#57]
Hello,
In 2015, an AMGx adapter was created within Trilinos's MueLU package [E. Furst, A. Prokopenko, J. Hu, 'Creating an AMGX adapter within the MueLu package', CCR Summer Proceedings 2015]. It is however restricted to a single GPU. Do you know whether work is currently being done (or planned) so as to make it work for more than a single GPU?
Thank you very much.
With best regards,
Serge

**Comment by piyueh** [comment]
Though off the topic, if you would like to use PETSc (which serves a similar purpose of Trilinos), you could try our AmgX wrapper for PETSc ([code repo](https://github.com/barbagroup/AmgXWrapper) & DOI: [10.21105/joss.00280](http://joss.theoj.org/papers/10.21105/joss.00280)). Our wrapper supports multiple GPUs sharing one computing node and also distributed GPUs (clusters). The wrapper only supports the MPIAIJ sparse matrix from PETSc.

**Comment by svancri** [comment]
Thanks for the hint.
What you did looks interesting and I will try to use it.
Best regards,
Serge

**Comment by marsaev** [comment]
@svancri 
No, we don't currently developing adaptors, but will be happy to list existing ones in the README.

@piyueh 
Can i list your AMGX wrapper for PETSc repo in the AMGX readme?

**Comment by piyueh** [comment]
@marsaev Yes, of course!
