### ISSUE TITLE
Can the library connect with other program by csr matrix but not mtx?

### ISSUE THREAD

**Issue by ningjiafei** [NVIDIA/AMGX#58]
Fron the paper"AMGX: A LIBRARY FOR GPU ACCELERATED ALGEBRAIC MULTIGRID AND PRECONDITIONED ITERATIVE METHODS∗", I know that AMGX library use **CSR matrix** itself.
Can I provide  the **CSR format** to AMGX to calculate directly?

**Comment by marsaev** [comment]
For single-rank application interface accepts csr data structure pointers.
For multi-rank application there are couple of interface functions one can use to provide csr data to AMGX. See for *upload* functions in the docs.

**Comment by ningjiafei** [comment]
> For single-rank application interface accepts csr data structure pointers.
> For multi-rank application there are couple of interface functions one can use to provide csr data to AMGX. See for _upload_ functions in the docs.

Thank you! I'll try it!
