### ISSUE TITLE
Compiling lib from scratch fails

### ISSUE THREAD

**Issue by Tongdongq** [NVIDIA/AMGX#59]
```
git clone https://github.com/NVIDIA/AMGX.git
cd amgx; mkdir build; cd build; cmake ..
```
This fails, because I don't pass any intended cuda architectures, when removing CMakeLists.txt:247, cmake runs successfully.

Running 'make' then results in an error around 7%:
amgx/core/src/classical/interpolators/distance2.cu(1343): error: identifier "sign" is undefined
          detected during:
            instantiation of "void amgx::distance2::compute_inner_sum_kernel<Value_type,CTA_SIZE,SMEM_SIZE,WARP_SIZE>(int, const int *, const int *, const Value_type *, const int *, const __nv_bool *, const int *, const int *, const int *, const int *, const Value_type *, const int *, Value_type *, int, int *, int *) [with Value_type=double, CTA_SIZE=256, SMEM_SIZE=128, WARP_SIZE=32]" 
(2418): here
            instantiation of "void amgx::Distance2_Interpolator<amgx::TemplateConfig<(AMGX_MemorySpace)1, t_vecPrec, t_matPrec, t_indPrec>>::generateInterpolationMatrix_1x1(amgx::Distance2_Interpolator<amgx::TemplateConfig<(AMGX_MemorySpace)1, t_vecPrec, t_matPrec, t_indPrec>>::Matrix_d &, amgx::Distance2_Interpolator<amgx::TemplateConfig<(AMGX_MemorySpace)1, t_vecPrec, t_matPrec, t_indPrec>>::IntVector &, amgx::Distance2_Interpolator<amgx::TemplateConfig<(AMGX_MemorySpace)1, t_vecPrec, t_matPrec, t_indPrec>>::BVector &, amgx::Distance2_Interpolator<amgx::TemplateConfig<(AMGX_MemorySpace)1, t_vecPrec, t_matPrec, t_indPrec>>::IntVector &, amgx::Distance2_Interpolator<amgx::TemplateConfig<(AMGX_MemorySpace)1, t_vecPrec, t_matPrec, t_indPrec>>::Matrix_d &, void *) [with t_vecPrec=(AMGX_VecPrecision)0, t_matPrec=(AMGX_MatPrecision)0, t_indPrec=(AMGX_IndPrecision)2]" 
(2521): here

Line 1343 indeed calls the function sign(), which is defined, but only as a __device__ function.
I do have cuda-10 installed, but the cuda-9.2 preceeds cuda-10 in $PATH.

**Comment by marsaev** [comment]
What host compiler do you have?

> I do have cuda-10 installed, but the cuda-9.2 preceeds cuda-10 in $PATH.
You can use CUDA_TOOLKIT_ROOT_DIR=/path/to/your/cuda yo use specific cuda for build/runtime (cmake builds with rpath)

**Comment by marsaev** [comment]
Line 1343 is a part of device code so that's fine.
Sign is defined later in this translation unit, so maybe your compiler don't like that.

**Comment by Tongdongq** [comment]
I have gcc 4.8.5, and a Tesla K40 (CC3.5).
I moved the definition of sign() line 647, right before the distance2 namespace.
It appears to work now, still compiling.

**Comment by marsaev** [comment]
Forgot to mention this issue in https://github.com/NVIDIA/AMGX/commit/b6b93592158df07a8c84d49c0c39e36023b1dba4
Should be fine now
