### ISSUE TITLE
Extra statistics AMG (like number of cycles)

### ISSUE THREAD

**Issue by lucasbekker** [NVIDIA/AMGX#65]
Would it be possible to accuire more statistics of the AMG solver by manipulating the config file?

I would be interested in (for example) the amount of cycles, the amount of levels per cycle and the matrix dimensions of the coarsest level of the cycle.

**Comment by lucasbekker** [comment]
"print_grid_stats" seems to provide a lot of what I need, shame that this isn't pointed out in the documentation...

**Comment by marsaev** [comment]
I'm not really sure what is amount of cycles and amount of levels per cycle. multigrid structure is available, as you figured out, with "print_grid_stats" specified for multigrid solver in config.

Right, it looks like pdf reference is not up to date. You might use AMGX_write_parameters_description() API to get available parameters, their descriptions and default values. Base parameters are being registered in core/src/core.cu

**Comment by marsaev** [comment]
Added task to check that all parameters are covered in docs: AMGX-54
