### ISSUE TITLE
GPUDirect with MPI

### ISSUE THREAD

**Issue by hkhetawat** [NVIDIA/AMGX#66]
I have been trying to run AMGX with GPUDirect enabled. There seem to be references in the code for GPUDirect but neither the examples, nor the documentation specifies how we can use the functionality. Is it implemented, and if so how can I enable it?

**Comment by marsaev** [comment]
It can be enabled by global config parameter 

> "communicator" : "MPI_DIRECT"

, see https://github.com/NVIDIA/AMGX/blob/a46b3112bc563592b8d794ba95e57350d282d584/core/src/core.cu#L362

**Comment by hkhetawat** [comment]
Does it go in the config file or in test code?

**Comment by marsaev** [comment]
In the config file

**Comment by hkhetawat** [comment]
Is there an example of a config file in the repo? I couldn't find one.

**Comment by hkhetawat** [comment]
Thanks! Got it.
