### ISSUE TITLE
Vastly different amount of iterations between host and device implementations

### ISSUE THREAD

**Issue by lucasbekker** [NVIDIA/AMGX#67]
I am testing FGMRES preconditioned with classical AMG on a Poisson matrix (2D unity square, 5 point stencil, 1000 elements, 1.000.000x1.000.000 matrix)

I ran the solver with the following json file:

{
    "config_version": 2,
    "determinism_flag": 1,
    "solver": {
        "preconditioner": {
            "solver": "AMG",
            "relaxation_factor": 0.75,
            "algorithm": "CLASSICAL",
            "cycle": "V",
            "max_iters": 3,
            "max_levels": 10,
            "smoother": "BLOCK_JACOBI",
            "presweeps": 1,
            "postsweeps": 2,
            "coarse_solver": "NOSOLVER",
            "coarsest_sweeps": 5,
            "print_grid_stats": 1
        },
        "solver": "FGMRES",
        "max_iters": 3000,
        "monitor_residual": 1,
        "tolerance": 1e-8,
        "convergence": "ABSOLUTE",
        "norm": "L2",
        "print_solve_stats": 1
    }
}

My choice of coarse level solver is dictated by the fact that no host implementation of a direct solver is available.

When I compare the runtime performance of solving the system on the host versus the device (hDDI vs dDDI), I find that the algorithm behaves very differently:

On the GPU:
AMGX version 2.0.0.130-opensource
Built on May 21 2019, 15:47:45
Compiled with CUDA Runtime 10.0, using CUDA driver 10.2
AMG Grid:
         Number of Levels: 10
            LVL         ROWS               NNZ    SPRSTY       Mem (GB)
         --------------------------------------------------------------
           0(D)      1000000           4996000     5e-06         0.0837
           1(D)       368525           3285599  2.42e-05         0.0883
           2(D)        78319            783647  0.000128         0.0207
           3(D)        17222            181738  0.000613        0.00477
           4(D)         4324             47276   0.00253        0.00124
           5(D)         1350             14124   0.00775       0.000373
           6(D)          451              4081    0.0201        0.00011
           7(D)          154              1104    0.0466       3.12e-05
           8(D)           53               301     0.107          9e-06
           9(D)           19                85     0.235       2.48e-06
         --------------------------------------------------------------
         Grid Complexity: 1.47042
         Operator Complexity: 1.86428
         Total Memory Usage: 0.199234 GB
         --------------------------------------------------------------
         Total Iterations: 1628
         Avg Convergence Rate: 		         0.9846
         Final Residual: 		   9.964285e-09
         Total Reduction in Residual: 	   9.984233e-12
         Maximum Memory Usage: 		          0.877 GB
         --------------------------------------------------------------

On the CPU:
AMGX version 2.0.0.130-opensource
Built on May 21 2019, 15:47:45
Compiled with CUDA Runtime 10.0, using CUDA driver 10.2
AMG Grid:
         Number of Levels: 10
            LVL         ROWS               NNZ    SPRSTY       Mem (GB)
         --------------------------------------------------------------
           0(H)      1000000           4996000     5e-06              0
           1(H)       368525           3285599  2.42e-05              0
           2(H)        89054            978244  0.000123              0
           3(H)        19212            213552  0.000579              0
           4(H)         4086             45600   0.00273              0
           5(H)          881              9793    0.0126              0
           6(H)          189              1993    0.0558              0
           7(H)           41               379     0.225              0
           8(H)           11                71     0.587              0
           9(H)            5                23      0.92              0
         --------------------------------------------------------------
         Grid Complexity: 1.482
         Operator Complexity: 1.90778
         Total Memory Usage: 0 GB
         --------------------------------------------------------------
         Total Iterations: 97
         Avg Convergence Rate: 		         0.7683
         Final Residual: 		   7.828256e-09
         Total Reduction in Residual: 	   7.843928e-12
         Maximum Memory Usage: 		          0.392 GB
         --------------------------------------------------------------

The most striking aspect is the amount of iterations: 1628 vs 97, but closer inspection reveals that the grid specifications also very significantly, which may very well be the cause of the different amount of iterations.

Could anyone tell me what causes these differences? (and how to prevent them from happening)

**Comment by marsaev** [comment]
Hi Lucas,

You are correct, it happens that depending on a problem (conditioning number, etc) solve might be very sensitive to the actual grid. 
About reproducibility. Classical solver with default parameters (PMIS selector, D1 interpolator) should have similar result for host and device. It's possible that math results on GPU and CPU might be different (i.e. parallel and serial FP accumulation), or it might be an issue/bug. I would assume that selector result is same - number of selected points for the second level is the same for both host and device (368525). If you are feeling adventurous enough - you can try comparing matrix values in the second level value by value and see if values are different for some of the points. If values are different it might lead to further difference in following layers.

P.S. note that you have NOSOLVER as coarsest level solver and number of coarsest sweeps is 5. You can set it to 1 without changing outcome - five times doing nothing on coarse level is same as doing nothing 1 time :)

**Comment by marsaev** [comment]
Also, it might be worth trying jacobi solver on the coarse level to help convergence

**Comment by marsaev** [comment]
Another note - for 5-point stencil on poisson it might be worth trying aggressive coarsening (see selectors for classical algorithms)

**Comment by jeaton32** [comment]
I would also recommend using D2 interpolation for device and host both. D1 still has some issues on GPU, and because D2 is always better we just moved to using D2 for everything.
Since this is a SPD Poisson problem, you also won't need FGMRES, or even GMRES here, just PCG should work with much less memory use.

**Comment by lucasbekker** [comment]
I will look into D2 interpolation.

FGMRES is used to minimize the amount of differences between the test cases

**Comment by RiverIntheSky** [comment]
I had a problem, for matrix size less than some threshold, only less than 20 iters are needed, once the size is larger than this threshold, more than 200 iters are needed... using D2 iterpolation solved this problem

**Comment by jeaton32** [comment]
There is a minimum 'coarse grid' size, below which a direct solver is used
in the multigrid method, which usually leads to many fewer iterations.
