### ISSUE TITLE
About matrix base index?

### ISSUE THREAD

**Issue by ningjiafei** [NVIDIA/AMGX#69]
I found that when I call the function **AMGX_matrix_upload_all**,the matrix **base index is 0**, that means data must counted like 0,1,2,3,4....
Howerver,the .mtx file seems like it's **base index is 1**?
Do you have text which could expain the **base index** in detail? Can I set all the matrix index as 1?

**Comment by marsaev** [comment]
default matrix reader is MatrixMarket (https://math.nist.gov/MatrixMarket/mmio/matlab/mmiomatlab.html) which is 1-based. Our `read system` functions automatically convert indices to 0-based which is what is used internally in AMGX. If you use upload functions with your data directly - they should be 0-based, `upload system` functions do not do this conversion.

**Comment by ningjiafei** [comment]
> default matrix reader is MatrixMarket (https://math.nist.gov/MatrixMarket/mmio/matlab/mmiomatlab.html) which is 1-based. Our `read system` functions automatically convert indices to 0-based which is what is used internally in AMGX. If you use upload functions with your data directly - they should be 0-based, `upload system` functions do not do this conversion.

Thanks for your reply!
