### ISSUE TITLE
Does amg solver support block matrices?

### ISSUE THREAD

**Issue by GitDjTHU** [NVIDIA/AMGX#73]
When using classical amg solver to solve a linear system with 3*3 block size, I met with the error

> Unsupported block size for strong connections

Then I checked with amgx code and found that there are many Error syntax as above.
![image](https://user-images.githubusercontent.com/7446752/62518725-c00b9f80-b85c-11e9-883b-f3e674c9a4c1.png)

Would you please let me know how to use amgx amg solver to solve such block matrix?

**Comment by marsaev** [comment]
Hi there,

Classical algorithm doesn't support block matrices, unfortunately. There is tentative work on block matrices support for classical, but i cannot give any estimations on when it will be available.

**Comment by GitDjTHU** [comment]
> 
> 
> Hi there,
> 
> Classical algorithm doesn't support block matrices, unfortunately. There is tentative work on block matrices support for classical, but i cannot give any estimations on when it will be available.

Unfortunately I have barely find any literature concerning about the block AMG algorithms. Is it meaningful to implement block-support or just using scalar AMG will work efficiently enough?

**Comment by marsaev** [comment]
I don't think there is definitive answer here and i don't know math that backs this up, but i think it's a good start to look at particular cases. As a "straightforward" solution i think it's possible to define some strength of connection based on blocks relation and implement interpolation for the blocks.
