### ISSUE TITLE
cusparseSetMatFullPrecision related build failure

### ISSUE THREAD

**Issue by lucasbekker** [NVIDIA/AMGX#75]
After the update to cuda V10.1.243, I get the following error while building AMGX:

../libamgxsh.so: undefined reference to `cusparseSetMatFullPrecision'

**Comment by lucasbekker** [comment]
The following changes to 'base/src/amgx_cusparse.cu' solved the build issue for me. I have not encountered any problems in my tests with this patch.

Line 68: From "return cusparseSetMatFullPrecision(cuMatDescr, true);" to "return CUSPARSE_STATUS_SUCCESS;"

Line 74: From "return cusparseSetMatFullPrecision(cuMatDescr, false);" to "return CUSPARSE_STATUS_SUCCESS;"

Line 80: From "return cusparseSetMatFullPrecision(cuMatDescr, false);" to "return CUSPARSE_STATUS_SUCCESS;"

**Comment by marsaev** [comment]
Hi Lucas. 
It was internal function for cusparse that enabled mixed precision for cusparse spmv. It was removed starting with mentioned release. cusparse now provide generic interface cusparseSpMV that allows this functionality. AMGX part responsible for cusparse spmv should be updated.

**Comment by lucasbekker** [comment]
SpMV is used everywhere, but I assume that my quick and dirty fix will only run into trouble when using mixed precision, is that correct?

**Comment by marsaev** [comment]
Correct. However it's even worse when you can't build the code :) Unfortunately generic spmv (https://docs.nvidia.com/cuda/cusparse/index.html#cusparse-generic-function-spmv) appeared pretty recently, so there should be ifdef on the cuda version.

**Comment by marsaev** [comment]
Should be fixed with https://github.com/NVIDIA/AMGX/pull/83
