### ISSUE TITLE
Dot Releases

### ISSUE THREAD

**Issue by levlafayette** [NVIDIA/AMGX#78]
Some release numbers would be good.

https://github.com/NVIDIA/AMGX/releases

You have a version ID, but that was six months ago and is associated with a release.

https://github.com/NVIDIA/AMGX/blob/master/ReleaseVersion.txt

**Comment by marsaev** [comment]
Thanks for the feedback.
Indeed changes/release tracking process is lacking. We will try to improve it and populate releases with proper changelog.

**Comment by marsaev** [comment]
We expect releases would be irregular, however development would be carried out in `main` branch.
