### ISSUE TITLE
Unsupported block size for strong connections

### ISSUE THREAD

**Issue by vmasyagin** [NVIDIA/AMGX#90]
Hello. I work with block matrices of different dimensions. Every time I come across this error:
Caught amgx exception: Unsupported block size for strong connections
 at: /home/victor/University/lib/AMGX/core/src/classical/strength/strength_base.cu:534
I see that this error occurs when using a block size above 1. I saw this issue: https://github.com/NVIDIA/AMGX/issues/73. Tell me, please, which solver to use in this case? Maybe there is a ready-made example of working with block matrices? Thank you in advance!

ps scalar matrices are disadvantageous to use, because memory overflow occurs on the device.

**Comment by marsaev** [comment]
Hey there,

Classical doesn't support block matrices fully (as explained in the mentioned issue) and there is no plans to add this support at the moment. For block matrices aggregation multigrid works right now, you can try configs with AGGREGATION, i.e. https://github.com/NVIDIA/AMGX/blob/master/core/configs/FGMRES_AGGREGATION_JACOBI.json
