### ISSUE TITLE
Hi is there any version for windows, like using visual studio?

### ISSUE THREAD

**Issue by miraboreasumr** [NVIDIA/AMGX#98]
Thank you for your time!

**Comment by marsaev** [comment]
Hey @miraboreasumr ,

We yet to compile list of supported environment which are confirmed to work, but in #87 we made Windows 10 with VS 2017 and CUDA 10.2 set up work.

**Comment by irfanms92** [comment]
Hi, 
I am able to successfully compile on Windows 10 with CUDA 10.2 on MSVS 2015. The library is getting compiled in Release build and failed in Debug build. The Debug issue is encountering from Thrust headers.

**Comment by marsaev** [comment]
@irfanms92 can you attach build log?

**Comment by marsaev** [comment]
There is known issue with modern Thrust and nvcc/msvc, unfortunately currently there is no known fix date, so on Windows only Release is supported.
